### ISSUE TITLE
1 of 33 tests failing; new mail hitting gmail is only getting processed on restarting ./inbox start

### ISSUE THREAD

**Issue by Analect** [nylas/sync-engine#10]
inbox app team:  Thanks for a great project. I had been looking for projects using zerorpc. I have been playing around with inbox today and have it mostly working except for a single test.  I wasn't sure if this was broken for you too?  Part of the error msg was "No handlers could be found for logger "inbox.server.general"" and I was wondering if this might explain why new mails hitting my gmail inbox aren't getting picked up and pushed across to mysql. I set up a workbench GUI to try to understand the tables in mysql a bit better ... the message and thread tables only appear to update when I stop and restart ./inbox start. As per the installation readme, I had set up ./inbox sync start myemail@gmail.com ... and wasn't sure if this was hindering new mails being picked up automatically. Thanks. Colum

runtest output is here: https://gist.github.com/Analect/f98543c05c39d763b307

**Comment by grinich** [comment]
FYI the (unsupported) Docker stuff is now here: https://github.com/nylas/sync-engine-docker
