### ISSUE TITLE
Include ElasticSearch install

### ISSUE THREAD

**Issue by florisgoumans** [nylas/sync-engine#103]
Currently the vagrant file does not include a ElasticSearch install, which would be very useful. 

Running on vagrant with the `bin/search-index-namespace` command will currently fail.

**Comment by thomasst** [comment]
In case someone is looking for the easiest way to get it running:
```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer
wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
dpkg -i elasticsearch-1.4.4.deb
/etc/init.d/elasticsearch start
/vagrant/bin/search-index-service
```

I haven't tested the search extensively though. Apart from "or" queries being broken, are there still any issues?

**Comment by grinich** [comment]
The search stuff isn't really part of the sync-engine project. If/when it's added, it will be a different service.
