### ISSUE TITLE
Exception on IMAP account Invalid inbox name

### ISSUE THREAD

**Issue by alokhan** [nylas/sync-engine#113]
Here is the exception I get from inbox, all the messages seems to be retrieved but this doesn't look nice so I report it.

Thanks for this great product btw :)

<code>
{"exception": "Traceback (most recent call last):\n\t  File \"/vagrant/inbox/util/concurrency.py\", line 74, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/vagrant/inbox/mailsync/backends/imap/generic.py\", line 245, in initial_sync\n    crispin_client.select_folder(self.folder_name, uidvalidity_cb)\n\t  File \"/vagrant/inbox/crispin.py\", line 590, in select_folder\n    self).select_folder(folder, uidvalidity_cb)\n\t  File \"/vagrant/inbox/crispin.py\", line 332, in select_folder\n    folder, readonly=self.readonly)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 359, in select_folder\n    self._command_and_check('select', self._normalise_folder(folder), readonly)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 928, in _command_and_check\n    self._checkok(command, typ, data)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 934, in _checkok\n    self._check_resp('OK', command, typ, data)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 902, in _check_resp\n    raise self.Error('%s failed: %r' % (command, data[0]))\n\terror: select failed: u'Invalid mailbox name.'\n", "account_id": 1, "level": "info", "timestamp": "2015-01-12T20:22:39.629954Z", "module": "inbox.crispin:234", "state": "initial", "greenlet_id": 91115920, "folder": "INBOX...", "event": "Connection broken with error; retrying with new connection"}
</code>

**Comment by spang** [comment]
hi @alokhan, thanks for the kind words! Could you share the output of the following?

    ./bin/inbox-console -e <your-email-address>

    crispin_client.folder_names()

This will help us diagnose your problem---it looks like we may be mangling one of the folder names in your account, which makes us unable to select it via the IMAP connection.

**Comment by alokhan** [comment]
Hi here it is, 

    Out[1]: 
    {'extra': [u'INBOX.Drafts',
    u'INBOX.Trash',
    u'INBOX.Junk',
    u'INBOX.Archive',
    u'INBOX.Sent',
    u'INBOX.Spam'],
    'inbox': u'INBOX'}

**Comment by grinich** [comment]
hey @alokhan

it looks like this is actually an issue with the IMAP response parser. Can you crank the crispin_client.conn.debug setting to 4 and output the full IMAP response?

**Comment by alokhan** [comment]
Hi how can I set the setting to 4 ? In the inbox settings file ? (/etc/inbox/settings.json)

**Comment by grinich** [comment]
I believe you can set `crispin_client.conn.debug = 4` when running `./bin/inbox-console`. That should print the raw IMAP responses.

**Comment by alokhan** [comment]
Ok sorry long time I didn't touch it, I had to update a lot of stuff :)

Here is the output with the debug set to 4 : 

17:09.312841 > HNDB4 LIST "" "*"
17:09.320237 < * LIST (\HasChildren) "." "INBOX"
17:09.320906 < * LIST (\HasNoChildren) "." "INBOX.Drafts"
17:09.321592 < * LIST (\HasNoChildren) "." "INBOX.Trash"
17:09.322251 < * LIST (\HasNoChildren) "." "INBOX.Junk"
17:09.322901 < * LIST (\HasNoChildren) "." "INBOX.Archive"
17:09.323653 < * LIST (\HasNoChildren) "." "INBOX.Sent"
17:09.324245 < * LIST (\HasNoChildren) "." "INBOX.Spam"
17:09.324817 < HNDB4 OK List completed.
Out[2]: 
{'archive': u'INBOX.Archive',
 'drafts': u'INBOX.Drafts',
 'extra': [u'INBOX.Junk', u'INBOX.Sent', u'INBOX.Spam'],
 'inbox': u'INBOX',
 'trash': u'INBOX.Trash'}

**Comment by grinich** [comment]
Hm, that looks OK. Have you still seen the original error?

**Comment by alokhan** [comment]
No actually I checked and the error is gone, I have another one concerning heartbeat but this will be for another issue :)

I guess this is solved ;)

**Comment by grinich** [comment]
OK, cool!  :smile:
