### ISSUE TITLE
Sync not working with supervisor

### ISSUE THREAD

**Issue by StefanIvanciuc** [nylas/sync-engine#117]
When I do:

```
cd inbox-path
bin/inbox-start
```

everything works fine. It sees new email right away.

But when I start it with supervisor:

```
user=inbox
directory=inbox-path
command=python bin/inbox-start
```

it almost never syncs new emails even it runs constantly.

Out log: http://laravel.io/bin/Yy5d6
Err log: http://laravel.io/bin/Gyq3P

PS: Tested on fresh local vm and works even with supervisor but on my server(the same arhitecture and stuff, the above situation occurs).

@khamidou

**Comment by grinich** [comment]
It looks like this isn't actually an issue with supervisor? Your trace seems to indicate errors with SSL, character decoding, or both.  For example:

[ERROR] {"exception": "Traceback (most recent call last):\n\t  File \"/home/inbox/inbox/inbox/util/concurrency.py\", line 74, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/home/inbox/inbox/inbox/sync/base_sync.py\", line 40, in _run_impl\n    self.poll()\n\t  File \"/home/inbox/inbox/inbox/sync/base_sync.py\", line 69, in poll\n    self.set_last_sync)\n\t  File \"/home/inbox/inbox/inbox/sync/base_sync.py\", line 96, in base_poll\n    items = provider_instance.get_items(last_sync)\n\t  File \"/home/inbox/inbox/inbox/events/base.py\", line 57, in get_items\n    for calendar_id, p_event, extra in self.fetch_items(sync_from_time):\n\t  File \"/home/inbox/inbox/inbox/events/google.py\", line 239, in fetch_items\n    service = self._get_google_service()\n\t  File \"/home/inbox/inbox/inbox/events/google.py\", line 78, in _get_google_service\n    http=http)\n\t  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/util.py\", line 132, in positional_wrapper\n    return wrapped(*args, **kwargs)\n\t  File \"/usr/local/lib/python2.7/dist-packages/apiclient/discovery.py\", line 192, in build\n    resp, content = http.request(requested_url)\n\t  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/util.py\", line 132, in positional_wrapper\n    return wrapped(*args, **kwargs)\n\t  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/client.py\", line 490, in new_request\n    redirections, connection_type)\n\t  File \"/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py\", line 1570, in request\n    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)\n\t  File \"/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py\", line 1317, in _request\n    (response, content) = self._conn_request(conn, request_uri, method, body, headers)\n\t  File \"/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py\", line 1252, in _conn_request\n    conn.connect()\n\t  File \"/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py\", line 1021, in connect\n    self.disable_ssl_certificate_validation, self.ca_certs)\n\t  File \"/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py\", line 80, in _ssl_wrap_socket\n    cert_reqs=cert_reqs, ca_certs=ca_certs)\n\t  File \"/usr/local/lib/python2.7/dist-packages/gevent/ssl.py\", line 383, in wrap_socket\n    ciphers=ciphers)\n\t  File \"/usr/local/lib/python2.7/dist-packages/gevent/ssl.py\", line 94, in __init__\n    self.do_handshake()\n\t  File \"/usr/local/lib/python2.7/dist-packages/gevent/ssl.py\", line 305, in do_handshake\n    return self._sslobj.do_handshake()\n\tSSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol\n", "account_id": 9, "level": "error", "timestamp": "2015-01-28T13:50:08.991780Z", "module": "inbox.util.concurrency:103", "greenlet_id": 99231536, "event": "Uncaught error"}
```
