### ISSUE TITLE
inbox.basicauth.OAuthError: Missing refresh token

### ISSUE THREAD

**Issue by StefanIvanciuc** [nylas/sync-engine#120]
Hi,

Lately I'm getting some issues with the GMail oauth and I'm unable to find any clues on how to fix it.
This happens when I'm trying to reauthenticate an email address.

Here is the complete error message:
http://laravel.io/bin/XynDO#

I'm using my own gmail client credentials.
Everything works fine at the initial login but after a while It just breaks.
In outlook for example I've never encountered this issue, although in both gmail and hotmail I never get asked to allow the app after the first login, it just issues an access code.

Does anyone have any suggestions on this?

Thanks.

**Comment by jennielees** [comment]
It sounds as though you are not asking for `offline` access after the first auth; if you've already granted access to the same set of scopes as previously, you won't see the consent screen and won't receive a refresh token.

However, this isn't in keeping with what your console output shows: you can see `access_type=offline` on line 16. When I try to reproduce this locally, I get the offline grant every time. Is it consistently happening for you on `--reauth`?

**Comment by grinich** [comment]
@StefanIvanciuc please open with more info if this is still an issue
