### ISSUE TITLE
Support for IMAP STARTTLS

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#121]
The inbox sync engine should add support for STARTTLS, since some IMAP servers use STARTTLS instead of a pure SSL/TLS connection.

**Comment by spang** [comment]
Hi @thomasst. We already support STARTTLS. We supported it before pure SSL/TLS even. :) Can you be more specific about what problem you're running into?

**Comment by thomasst** [comment]
Which code is responsible for doing STARTTLS? When I try to connect with to an IMAP account with port 143 it tries to do pure SSL/TLS in inbox.auth.generic:65 and I get the following error (replaced my actual email with example.com). I couldn't find any references to STARTTLS in the code.

```
{"level": "error", "timestamp": "2015-03-02T22:00:16.683834Z", "error": "[ALERT] (Failure): [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol", "module": "inbox.auth.generic:78", "event": "account_connect_failed", "email": "email@example.com", "host": "example.com", "greenlet_id": 75349520, "port": 143}
```

**Comment by emfree** [comment]
imapclient doesn't currently support STARTTLS: https://bitbucket.org/mjs0/imapclient/issue/97/starttls-support. I think Menno is planning to add this in the 1.0.0 release of imapclient.

**Comment by thomasst** [comment]
We patch imaplib to add STARTTLS on Python 2.x and use imapclient with it. Would you be interested in a pull request if I implemented it in inbox?

**Comment by grinich** [comment]
I think a lot of users of N1 need STARTTLS support https://github.com/nylas/N1/issues/47

**Comment by mjs** [comment]
I can confirm that IMAPClient 1.0 has STARTTLS support

**Comment by spang** [comment]
@grinich Do you have evidence that this is actually an issue with IMAP STARTTLS? It looks like those N1 users are having trouble with SMTP settings, which is completely unrelated.

We actually currently support IMAP STARTTLS via the monkeypatch that @thomasst contributed a while back in f6f9d4e75a2ca88cb65d31bde96353e74e4e0984. (Yes, we should port to IMAPClient 1.0 and make that code go away, but for the time being I believe it still works.)
