### ISSUE TITLE
Retry on IMAP connection errors is too aggressive

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#123]
When there's an IMAP connection error, geventpool uses intervals starting from 0.1s doubling to over 400s (in `ConnectionPool._addOne`). Since the default read connection pool size is 3, this interval is per connection and inbox sync issues way too many reconnection attempts.

Suggestions:
* Only open an additional connection if the previous connection succeeds, instead of immediately trying to connect 3 times
* Use less aggresive different retry intervals, e.g. start at 60s and increase until it hits e.g. 10mins or more.

**Comment by spang** [comment]
We rewrote this back in late May.
