### ISSUE TITLE
'docker-compose up' failing on installing inbox-start script

### ISSUE THREAD

**Issue by Analect** [nylas/sync-engine#131]
Hi.
Just renamed fig.yml as docker-compose.yml (the fig replacement) and all seemed to be going well until it hit this permissioning issue.  I was under the impression that in a container, you are root by default ... and that this inbox-start script was being installed in the container ... so not sure why this is failing.  Any thoughts on what I might tweak to get this working?
Thanks. Colum

From docker ps -a, the mysql container was created OK ... but the inbox one (top one) aborted on the error down below.
IMAGE                                  COMMAND                CREATED             STATUS                        PORTS                                                            NAMES
29cd0638aa71        2cf79600441b                           "/bin/sh -c '/srv/in   2 minutes ago       Exited (1) 2 minutes ago                                                                       elegant_hodgkin           
fb2f66bef382        mysql:5.5                              "/entrypoint.sh mysq   12 minutes ago      Up 12 minutes                 3306/tcp                                                         inbox_inboxdb_1           

running build_ext
Creating /usr/local/lib/python2.7/dist-packages/inbox-sync.egg-link (link to .)
Adding inbox-sync 0.4 to easy-install.pth file
Installing inbox-start script to /usr/local/bin
error: /usr/local/bin/inbox-start: Permission denied

----------------------------------------
Command /usr/bin/python -c "import setuptools; __file__='/srv/inbox/setup.py'; exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps failed with error code 1 in /srv/inbox
Storing complete log in /home/admin/.pip/pip.log
Service 'inbox' failed to build: The command [/bin/sh -c /srv/inbox/docker/postinstall-src /srv/inbox &&     install -m0755 docker/inbox-cron-hourly /etc/cron.hourly/inbox-cron-hourly &&     install -m0755 docker/inbox-cron-daily /etc/cron.daily/inbox-cron-daily &&     install -m0755 docker/inbox-cron-weekly /etc/cron.weekly/inbox-cron-weekly &&     install -m0755 docker/inbox-cron-monthly /etc/cron.monthly/inbox-cron-monthly] returned a non-zero code: 1

**Comment by Analect** [comment]
I played around with this a little further with this, hoping to get around the permissioning error above. I suspect I may not be approaching a fix the right way, in which case I'm very open to pointers!

I changed line 61 of the dockerfile from 'chown -R admin ....' to 'chown -R root ...' ... as I said, this might not be the right approach ... and then stumbled on this.

I suspect I need to tweak something .... remove the half-baked images that the 'docker-compose up' has attempted ... and try to rebuild again.

REPOSITORY                            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                                <none>              f10509f50d24        8 hours ago         696.7 MB
<none>                                <none>              2cf79600441b        3 days ago          696.7 MB
mysql                                 5.5                 c8defdc7b8fa        8 days ago          214.5 MB
debian                                wheezy              d5570ef1464a        8 days ago          84.98 MB


Installing collected packages: cpu-affinity, inbox-sync
  Running setup.py install for cpu-affinity
    error: could not create '/usr/local/lib/python2.7/dist-packages/affinity': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/srv/inbox/build/cpu-affinity/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-EYtSw3-record/install-record.txt:
    running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/affinity
copying affinity/__init__.py -> build/lib.linux-x86_64-2.7/affinity
running install_lib
creating /usr/local/lib/python2.7/dist-packages/affinity
error: could not create '/usr/local/lib/python2.7/dist-packages/affinity': Permission denied

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/srv/inbox/build/cpu-affinity/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-EYtSw3-record/install-record.txt failed with error code 1 in /srv/inbox/build/cpu-affinity
Storing complete log in /home/admin/.pip/pip.log
Service 'inbox' failed to build: The command [/bin/sh -c /srv/inbox/docker/postinstall-src /srv/inbox &&     install -m0755 docker/inbox-cron-hourly /etc/cron.hourly/inbox-cron-hourly &&     install -m0755 docker/inbox-cron-daily /etc/cron.daily/inbox-cron-daily &&     install -m0755 docker/inbox-cron-weekly /etc/cron.weekly/inbox-cron-weekly &&     install -m0755 docker/inbox-cron-monthly /etc/cron.monthly/inbox-cron-monthly] returned a non-zero code: 1

**Comment by Analect** [comment]
@aidanhs @dlitz 
I know you made some changes back in December ref running as root versus admin.
I only managed to get the dockerfile build / docker-compose working when I changes lines 26 and 30 of https://github.com/nylas/sync-engine/blob/master/docker/postinstall-src to 'root' from 'admin'.
Documenting here in case others have similar problems.

**Comment by grinich** [comment]
@Analect want to submit a PR?

**Comment by Analect** [comment]
Added PR here: https://github.com/nylas/sync-engine/pull/134
Not sure if this is the right approach.

**Comment by grinich** [comment]
FYI the (unsupported) Docker stuff is now here: https://github.com/nylas/sync-engine-docker
