### ISSUE TITLE
role played by redis? ... and specifying more detailed config file in dockerized version

### ISSUE THREAD

**Issue by Analect** [nylas/sync-engine#133]
I resolved a problem with docker-compose on #131 
For a separate app, I have a redis server exposed on port 6379. This is somehow conflicting with the redis set-up for inboxapp (see ref error 111 below). What is redis doing in the inboxapp and is it expected to run from within the syncengine_inbox_1 container? If so, should the fig.yml get updated to require a redis server to be started.
I'm hoping I can just change the conflicting port in the config for inboxapp to something like 6380, if it does require it's own dedicated redis.
In terms of config, I can see a minimal file in /run/inboxapp/config.json in the syncengine_inbox_1 container, which just has some basic mySQL credentials and doesn't include any redis settings. There are more detailed config files in /srv/inbox/etc that do include redis setting. Should any of these be used in the docker build instead?  Thanks.

console log:
inbox_1   | {"exception": "Traceback (most recent call last):\n\t  File \"/srv/inbox/inbox/heartbeat/store.py\", line 14, in wrapper\n    return f(*args, **kwargs)\n\t  File \"/srv/inbox/inbox/heartbeat/store.py\", line 136, in publish\n    self.client.hset(key, device_id, value)\n\t  File \"/usr/local/lib/python2.7/dist-packages/redis/client.py\", line 1853, in hset\n    return self.execute_command('HSET', name, key, value)\n\t  File \"/usr/local/lib/python2.7/dist-packages/redis/client.py\", line 570, in execute_command\n    connection.send_command(*args)\n\t  File \"/usr/local/lib/python2.7/dist-packages/redis/connection.py\", line 556, in send_command\n    self.send_packed_command(self.pack_command(*args))\n\t  File \"/usr/local/lib/python2.7/dist-packages/redis/connection.py\", line 532, in send_packed_command\n    self.connect()\n\t  File \"/usr/local/lib/python2.7/dist-packages/redis/connection.py\", line 436, in connect\n    raise ConnectionError(self._error_message(e))\n\tConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "account_id": 1, "level": "error", "timestamp": "2015-04-06T16:46:43.583819Z", "module": "inbox.heartbeat.store:17", "state": "poll", "greenlet_id": 101617168, "folder": "[Gmail]/All Mail", "event": "Error interacting with heartbeats"}

**Comment by jennielees** [comment]
The redis store is used in the heartbeat mechanism, which tracks alive/dead status of accounts. Should probably pull in the config from `etc` - the docker config predates this requirement. A custom port should be respected :)

**Comment by alokhan** [comment]
Is redis starting automatically when starting inbox ?

**Comment by grinich** [comment]
Just a FYI, we're not using Docker anywhere in our production environment and haven't done much work on it at all. :disappointed:

**Comment by grinich** [comment]
FYI the (unsupported) Docker stuff is now here: https://github.com/nylas/sync-engine-docker

**Comment by grinich** [comment]
FYI the (unsupported) Docker stuff is now here: https://github.com/nylas/sync-engine-docker
