### ISSUE TITLE
AGPL license clarification: does using the API constitute a derivative work

### ISSUE THREAD

**Issue by funkyeah** [nylas/sync-engine#135]
If a program uses the API of an AGPL licensed program there is some contention on whether that program is a derivative piece of work (and must have its source code released) or not. Some (like MongoDB) say it is not a derivative work and you only have to disclose modifications to MongoDB and not the code of your program at large. Others disagree.

I have done a fair bit of reading on this and the general consensus seems to be to ask whomever is licensing code as AGPL for clarification of the intent.

So does a program's use of the AGPL licensed sync-engine require disclosure of the program's entire source code or only disclosure of modifications made to the sync-engine directly?

**Comment by grinich** [comment]
Only modifications to the sync engine or components it directly interacts with (such as its specific MySQL database).

Using it via the standard REST APIs requires no disclosure.
