### ISSUE TITLE
Feature Request: Last active participant on thread object

### ISSUE THREAD

**Issue by bictorman** [nylas/sync-engine#138]
I just hit a wall trying to display the last person to send a message on the thread list. From what I could gather it looks like currently I'd need to make an extra request for every thread's message, while easily cacheable it still seems a quite costly.

In the same fashion as the timestamp, it would be really useful to display the first and last sending participants, either with the a full participant object, with just the email or with the index within the participants array.

Eg.

```json
"first_message_timestamp": 1430232210,
"last_message_timestamp": 1430232595,
"first_message_from_participant": 0,
"last_message_from_participant": 2,
```

**Comment by yodaiken** [comment]
+1

**Comment by grinich** [comment]
The way we do this right now is through the expanded thread view. Try adding `view=expanded`.

**Comment by bictorman** [comment]
How can I have missed that feature! Sorry for cluttering the issue list, next time I'll ask via email first.
