### ISSUE TITLE
Email accounts are not retried properly (stuck in connection pool lock)

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#141]
When a syncing error occurs, accounts are never retried. For example:

> {"exception": "Traceback (most recent call last):\n\t  File \"/home/ubuntu/inbox/inbox/util/concurrency.py\", line 73, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/home/ubuntu/inbox/inbox/mailsync/backends/imap/generic.py\", line 273, in initial_sync\n    self.initial_sync_impl(crispin_client)\n\t  File \"/home/ubuntu/inbox/inbox/mailsync/backends/imap/generic.py\", line 320, in initial_sync_impl\n    self.download_uids(crispin_client, download_stack)\n\t  File \"/home/ubuntu/inbox/inbox/mailsync/backends/imap/generic.py\", line 406, in download_uids\n    [uid])\n\t  File \"/home/ubuntu/inbox/inbox/mailsync/backends/imap/generic.py\", line 503, in download_and_commit_uids\n    raw_messages = safe_download(crispin_client, uids)\n\t  File \"/home/ubuntu/inbox/inbox/mailsync/backends/imap/generic.py\", line 595, in safe_download\n    raw_messages = crispin_client.uids(uids)\n\t  File \"/home/ubuntu/inbox/inbox/crispin.py\", line 508, in uids\n    ['BODY.PEEK[] INTERNALDATE FLAGS'])\n\t  File \"/home/ubuntu/inbox/src/imapclient/imapclient/imapclient.py\", line 831, in fetch\n    typ, data = self._imap._command_complete('FETCH', tag)\n\t  File \"/usr/lib/python2.7/imaplib.py\", line 909, in _command_complete\n    typ, data = self._get_tagged_response(tag)\n\t  File \"/usr/lib/python2.7/imaplib.py\", line 1016, in _get_tagged_response\n    self._get_response()\n\t  File \"/usr/lib/python2.7/imaplib.py\", line 928, in _get_response\n    resp = self._get_line()\n\t  File \"/usr/lib/python2.7/imaplib.py\", line 1026, in _get_line\n    line = self.readline()\n\t  File \"/usr/lib/python2.7/imaplib.py\", line 1188, in readline\n    return self.file.readline()\n\t  File \"/usr/lib/python2.7/socket.py\", line 447, in readline\n    data = self._sock.recv(self._rbufsize)\n\t  File \"/usr/local/lib/python2.7/dist-packages/gevent/ssl.py\", line 208, in recv\n    return self.read(buflen)\n\t  File \"/usr/local/lib/python2.7/dist-packages/gevent/ssl.py\", line 110, in read\n    return self._sslobj.read(len)\n\terror: [Errno 104] Connection reset by peer\n", "account_id": 1, "level": "info", "timestamp": "2015-05-11T17:33:22.277750Z", "module": "inbox.crispin:263", "state": "initial", "greenlet_id": 140278322330192, "folder": "Sent Items", "event": "Connection broken with error; retrying with new connection"}
> {"account_id": 1, "level": "info", "timestamp": "2015-05-11T17:33:59.279895Z", "module": "inbox.mailsync.backends.imap.generic:266", "state": "initial", "greenlet_id": 140278322330192, "folder": "Sent Items", "event": "starting initial sync"}

Nothing happens after this. When investigating the issue it looks like it's stuck in `inbox.mailsync.backends.imap.generic.FolderSyncEngine.initial_sync` at the following line:
```
with self.conn_pool.get() as crispin_client:
```

which is stuck in geventpool's `ConnectionPool.get` method in `self.lock.acquire()`

Seems like the lock is not properly released when an exception occurs?

**Comment by grinich** [comment]
What type of account is this for?

This is running the latest version?

**Comment by thomasst** [comment]
It's the name.com IMAP server. I'm running a slightly modified but recent version of nylas but I can double check later with the latest master.

**Comment by emfree** [comment]
Replaced geventconnpool with a better implementation in 400381b. Please reopen if you observe sync stuckness or other bad behavior.
