### ISSUE TITLE
API should indicate message folders

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#143]
When fetching a thread, it is unclear which messages are in a given folder. This is specifically a problem with the trash and spam folders. I tested this on a non-Gmail IMAP server where one message was in the inbox and the other was in the trash. Nylas would apply both the inbox and trash tag to the thread but not indicate which of the messages are in the inbox or the trash.

The suggested fix would be to return the IMAP folder or a list of tags for each message. This gives most flexibility. Alternatively, an `is_trash`, `is_spam` flag could be returned for each message.

**Comment by grinich** [comment]
we're working on this

**Comment by grinich** [comment]
This is solved with the new labels+folders APIs :+1: :100:
