### ISSUE TITLE
Invalid email from contact API call

### ISSUE THREAD

**Issue by Eagles2F** [nylas/sync-engine#144]
Hi guys from nylas,  
     I've encountered a very weird result from my contact api call.
   
  The call:
   ```  curl --user '[token]:'   https://api.nylas.com/n/[token]/contacts ```
       
   The result:
     ```
    {
        "email": "a",
        "id": "exow62aopx9ri76g9zj2z5ev5",
        "name": "",
        "namespace_id": "6crmotdd8672o6wlhxi001bhf",
        "object": "contact"
    },
     ```
 As you can see, the email address is "a".   I believe this is a bug from sync engine. I've set up a local validation mechanism for this. Just hope you guys could also look into it.

**Comment by spang** [comment]
Hi @Eagles2F. Thanks for the report! We've also seen this happen, but aren't quite sure what causes it yet. If you can manage to reproduce it reliably, that would help us fix it a lot quicker. :)

**Comment by Eagles2F** [comment]
@spang  If I provided my full api call to you guys ,will that be helpful?

**Comment by spang** [comment]
This is likely a bug in the creation of contacts, so unfortunately knowing the API call to access the bad contact isn't that useful.

**Comment by Eagles2F** [comment]
I wish I could help something with the contactAPI.  Because the contact API again send me something weird like "email":null,"name":"Zhang Jinrun".

**Comment by jennielees** [comment]
What is the underlying account type you are syncing? (Gmail?)

**Comment by Eagles2F** [comment]
gmail.
