### ISSUE TITLE
"[AUTHENTICATIONFAILED]" should always trigger ValidationError

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#153]
`[AUTHENTICATIONFAILED] Invalid username or password` (without trailing period) is a response from `mail.me.com` which is in not `inbox.auth.generic.AUTH_INVALID_RESPONSES`. Nylas therefore doesn't trigger a validation error. A better way would be for `connect_account` to check for  `exc.message.startswith('[AUTHENTICATIONFAILED]')` or have a separate method that takes the error string as an argument and returns True/False based on whether it's an authentication error.

**Comment by thomasst** [comment]
Some other messages that aren't covered:
* `Login failed.` (imap.secureserver.net)
* `LOGIN failed.` (outlook.office365.com IMAP)

**Comment by emfree** [comment]
Fixed in 79be46c
