### ISSUE TITLE
Large Gmail accounts fail with "abort: command: UID => System Error"

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#160]
We can't do a search for `X-GM-LABELS inbox` in the All Mail folder for large Gmail accounts. It will fail with `abort: command: UID => System Error `. Here's my workaround: https://github.com/elasticsales/inbox/commit/b83bd8df919827a75c60291848407a52afd04189

I wasn't sure whether to simply change the `if self.is_all_mail(crispin_client):` clause to `if self.is_all_mail(crispin_client) and remote_uid_count < 1e6:`, so I decided to go the safer route and skip the search.

**Comment by spang** [comment]
We fixed this in 44335b83ac3aba234b45bd3586f88d14b96afb59.
