### ISSUE TITLE
Trash folder shouldn't be required to sync a Gmail account

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#163]
Nylas should be able to sync a Gmail account even if it doesn't have a Trash folder.

The following implementation lets you sync accounts that doesn't have trash folders. What's missing is proper handling of deletions initiated through Nylas.

https://github.com/elasticsales/inbox/commit/375f5f972f6830756a43c510c78596fa3f641d11
https://github.com/elasticsales/inbox/commit/125d7fc76ecb314dca0429ccf6bc8e353c194048

**Comment by jennielees** [comment]
We added this requirement because we were running into errors when a user without a Trash folder was trying to delete items. We don't hard-delete, but move deleted items to Trash, so without implementing alternative delete handling we can't relax the Trash requirement.

**Comment by kav-ya** [comment]
To add to what @jennielees said, we're revisiting this decision as part of our fix to #156 and #136. We plan to make the 'All Mail' folder the only required one for Gmail and for generic IMAP, the 'INBOX' folder.

**Comment by Eagles2F** [comment]
Hi, I've just came across the discussion here. If Nylas is doing what @kav-ya  proposed, does that mean there are no longer 8 standard labels/folders since only ALL MAIL is required?

**Comment by thomasst** [comment]
I think this is fixed in the latest version (only INBOX / All Mail are required). The appropriate labels should still be there if the folder exists.

If you agree this is fixed, feel free to close this.

**Comment by Eagles2F** [comment]
Sorry, I'm not sure how's implemented in the newest sync engine. But according to the exposure of the new folder/label api: https://www.nylas.com/docs/platform/api_folders, there are 8 standard labels.
