### ISSUE TITLE
Archive folder creation/deletion handling

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#164]
* If the Archive folder is deleted by the client, the tag shouldn't be removed https://github.com/elasticsales/inbox/commit/b2d571e29d19cee2a16168126488cf736ff75467
* If creating the Archive (and possibly any other folders) fails with `Invalid mailbox name`, Nylas should assume there is an IMAP folder prefix and attempt to create `INBOX.Archive`. https://github.com/elasticsales/inbox/commit/da571cfe07e308c43cb27bb471b6f67789bfd345

**Comment by grinich** [comment]
Going to close as invalid since this predates the labels+folders APIs.
