### ISSUE TITLE
Not supported mail provider

### ISSUE THREAD

**Issue by Eagles2F** [nylas/sync-engine#177]
Hi  Nylas folks, 
 I find out that we need to input SMTP servers and IMAP servers by ourselves when logging into some Chinese Mail providers. I'm thinking about doing a pull request to the repo with some mail provider and server matches to the list you guys are using. Will this be helpful ?  

  Not supported server like xx@163.com: 
     smtp: smtp.163.com  ssl:465   
     imap: imap.163.com  ssl: 993

**Comment by khamidou** [comment]
Sure! However, you'll need to sign our [Contributor License Agreement](https://www.nylas.com/cla.html) before we can merge your pull request.

Karim
