### ISSUE TITLE
In query parameter doesn't work for ID

### ISSUE THREAD

**Issue by Eagles2F** [nylas/sync-engine#179]
Quote from doc:https://www.nylas.com/docs/platform/api_folders
     " The in parameter is the folder or label’s name, display_name or ID."
And I tried for my gmail account, in query parameter only works for name and display_name

**Comment by kav-ya** [comment]
@Eagles2F, thanks for the report! The bug has been fixed in commit 301d9.

**Comment by Eagles2F** [comment]
@kav-ya  thanks. How long it usually takes to see the change in the hosted version?

**Comment by spang** [comment]
@Eagles2F for small features, it should go live within 24 hours. Larger features may require more extensive final QA before going live on the hosted service. This feature is currently live in production on our hosted service.

**Comment by Eagles2F** [comment]
@spang  gotcha, thanks.
