### ISSUE TITLE
Can't apply filter "view=expanded" to the PUT request

### ISSUE THREAD

**Issue by Eagles2F** [nylas/sync-engine#181]
"view=expanded" works fine for "GET" request.  But when I'm changing label which is done by doing PUT request, the return result can not be expanded.    I'm not sure is this a design decision or simply a problem.

**Comment by grinich** [comment]
@Eagles2F On what object/endpoint?

**Comment by grinich** [comment]
This is a design decision. We don't support the expanded param on PUT requests which modify objects.
