### ISSUE TITLE
Filter events by participants

### ISSUE THREAD

**Issue by AdriVanHoudt** [nylas/sync-engine#186]
Is this something that can be added? Seems like a standard thing to do?

**Comment by grinich** [comment]
Can you be a bit more specific to what you're looking for?

**Comment by AdriVanHoudt** [comment]
It would be a filter where I can query all the events and get back the
events including email address A (and email address B) as participant

**Comment by spang** [comment]
Taking a look, I don't see why we shouldn't be able to add this filter. It'd be very similar to what we offer with our thread and messages filters. No one's asked for something like this yet is all. :) The most common thing people do with the events API is download spans of events by date.

**Comment by grinich** [comment]
W store event participants as [serialized JSON](https://github.com/nylas/sync-engine/blob/master/inbox/models/event.py#L129), so I think this would require a LIKE query and be quite slow.

**Comment by AdriVanHoudt** [comment]
Yeah a quick look told me it is like the to from a message no? Would it be possible to do it the same way?

**Comment by AdriVanHoudt** [comment]
@grinich the to from a message is also stored like that no? https://github.com/nylas/sync-engine/blob/master/inbox/models/message.py#L57

**Comment by grinich** [comment]
[internal] https://phab.nylas.com/T3354

**Comment by grinich** [comment]
@AdriVanHoudt there's a separate table for looking up message participants called the [Message Contact Association](https://github.com/nylas/sync-engine/blob/c9d81d25b7552691748fb0de94a6335b25c21a4b/inbox/models/contact.py#L57) which makes that kind of query fast. In order to add filtering events by participants, we'll need to add a similar association table for events that's updated during event sync, and also run a migration to back-populate it for all existing events.

It's all doable-- just isn't a super quick thing to add. ;)

**Comment by AdriVanHoudt** [comment]
@grinich it is something we really need though, can I help speed this up in any way?

**Comment by AdriVanHoudt** [comment]
Also I do believe the `/files` endpoint also doesn't have this (docs are down atm so can't check)

To clarify our use case: we show a lot of info about interactions between the user and certain contacts (this includes files, messages, events and a bunch of our own logging stuff) so we need to be able to filter the user's data by contacts(/participants). To us this seems a very logical filter to have and we already have this working with contextio so we need this for our switch to Nylas.

**Comment by grinich** [comment]
I totally understand the use case, and I'm certainly not arguing with it. (These are features I'd like to see as well.) We just have a small engineering team with several projects currently in-flight, so we can't add it to the roadmap immediately, given the relative complexity of the change+migration.

Fastest way to speed this up would be for you to build it and submit a PR :wink: but barring that, maybe you could hop on a call with our BD team if you're looking at using the Nylas hosted platform? Having a defined sales contract helps us prioritize customer needs and justify tradeoffs for engineering time on additional features like this. (You're the first one who's asked for this.)

**Comment by AdriVanHoudt** [comment]
I will look into a PR (never have done python before :P) and we were on a call with Gleb yesterday and will be with Christine Spang (and Gleb) on thursday so we can probably discuss this further then.

**Comment by grinich** [comment]
OK, great. 

Docs had just moved by the way. You can find them here: https://nylas.com/docs

**Comment by AdriVanHoudt** [comment]
jup just found them, looks nice
