### ISSUE TITLE
Is there any API for fetching the message body only?

### ISSUE THREAD

**Issue by kitgary** [nylas/sync-engine#187]
I am looking for an API to fetch the message body only.

**Comment by grinich** [comment]
You mean something other than the `/messages` endpoint?

**Comment by kitgary** [comment]
I want to fetch only the message body with some api like this
https://api.nylas.com/n/<namespace_id>/messages/<message_id>?content=body

Because I am currently using
https://api.nylas.com/n/<namespace_id>/threads?view=expanded
to grab the thread information and also the message metadata, the only missing content here is the body.

So I don't want to grab all message information again and get only the message body when getting into the thread.

**Comment by grinich** [comment]
What's wrong with just calling `https://api.nylas.com/n/<nsid>/messages/<message_id>` and just using the `body` param? 

You get back a few extra parameters, but you can just disregard them.

**Comment by kitgary** [comment]
No. I just wonder if there is any API is capable to grab part of the message data. Ok, I can discard unused parameters. Thanks.

**Comment by grinich** [comment]
Not right now, but maybe in the future!
