### ISSUE TITLE
attachment image vs content image

### ISSUE THREAD

**Issue by Eagles2F** [nylas/sync-engine#189]
Hi folks,  
   I found there are some undefined area regarding attachment images and content images.

   Say I'm using gmail to send an email with my personal logo in the email content and another picture of my vacation to a friend.  Using Nylas sync engine,  on the friend's side, he will receive an email with two attachments, which makes him difficult to distinguish which is the real attachment.

   This can cause more problem like if I'm forwarding an email with a content image like logo. Every message following this forwarding will include the logo as the attachment since it's in the "Quote" area. This makes Mailfile list grow and grow.   

   I'm thinking probably we should distinguish between attachments and resources in the mailFile properties. What do you guys think?

**Comment by grinich** [comment]
Inline attachment objects should have the `content_id` property, which matches the inline `cid:xxxxx` image tag attribute.

Are you seeing different behavior? What other distinguishing information are you suggesting?

**Comment by Eagles2F** [comment]
@grinich  I agree with your proposal about having something like "content_id"

**Comment by grinich** [comment]
It's not a proposal-- it's already in the API.

What is "mailfile api"?

**Comment by Eagles2F** [comment]
By api, do you mean this one? https://www.nylas.com/docs/platform/api_files

**Comment by grinich** [comment]
Yes, they should include a `content_id` property for inline attachments. Similarly the `files` attribute in a message has them too.

**Comment by Eagles2F** [comment]
Thank you @grinich . Gonna verify this.

**Comment by Eagles2F** [comment]
I just verified any content_image which means inline image will have the field "content_id". If the images are attachments, they won't have this field.

**Comment by grinich** [comment]
Not sure what you mean by `content_image` but I'm going to close this anyway since it sounds like everything is working correctly.
