### ISSUE TITLE
Does "hide" the exception

### ISSUE THREAD

**Issue by jakobdo** [nylas/sync-engine#192]
Why not throw the exception?

https://github.com/mailgun/flanker/blob/master/flanker/mime/message/headers/encodedword.py#L75-L82

We have seen an email with "buggy" subject. Flanker fails, but we have no way to catch the exception.

Snip of email:

To: <user@domain.tld>
From: <noreply@domain.tld>
Reply-To: <servicedesk@domain.tld>
Subject: W�RTZ
Date: Thu, 20 Aug 2015 06:01:03 +0200
MIME-Version: 1.0
Content-Type: text/plain

**Comment by spang** [comment]
Hi @jakobdo,

I tried reproducing this issue, and the snippet you provided parses fine in flanker when I try it. Can you provide a concrete example to reproduce?
