### ISSUE TITLE
Sync without emails (contacts and calendars only)?

### ISSUE THREAD

**Issue by laander** [nylas/sync-engine#193]
Hi, we'd like to use the sync engine for primarily syncing calendar events and contacts. Is there any way we can disable email sync altogether? Also, which calendar providers are currently supported? Thanks!

**Comment by grinich** [comment]
The sync engine is primarily designed to sync mail. There's currently no way to sync calendars/contacts without mail.

**Comment by grinich** [comment]
This is now supported by disabling the `sync_email` attribute of an account.
