### ISSUE TITLE
Improper, undocumented canonization of @googlemail.com accounts

### ISSUE THREAD

**Issue by justjanne** [nylas/sync-engine#202]
**How to reproduce**:

1. `bin/inbox-auth name@googlemail.com`
2. `bin/inbox-sync start name@googlemail.com`

**What should happen**:

Start synchronizing, or warns about @googlemail being canonized to @gmail.com

**What happens**:

`No record of account name@googlemail.com`

**Comment by pyhedgehog** [comment]
Could it be so that you "`name`" contains dots?

**Comment by justjanne** [comment]
Yes, it does.

But it properly returns "firstname.lastname@google.com", instead of working with "firstname.lastname@googlemail.com"

**Comment by pyhedgehog** [comment]
`@google.com` or `@gmail.com`?

**Comment by justjanne** [comment]
eh, sorry.

It does work with @gmail.com, but does not work with @googlemail.com

**Comment by pyhedgehog** [comment]
It's really strange. Only special thing I've found about gmail/googlemail account canonicalization is removing dots from local name:
https://github.com/nylas/sync-engine/blob/dae94ada8c7327255dabb952314a34e9bf13c2cc/inbox/util/addr.py#L21

**Comment by justjanne** [comment]
Google returns, as canonical name, for all `@googlemail.com` accounts
`@gmail.com`.

Maybe add a special case to return the domain that the user entered?

Expected Behaviour:

* User enters first.last@googlemail.com

* Google returns firstlast@gmail.com

* Nylas returns first.last@googlemail.com to the user.

Effectively, just don’t canonize the domain the user entered.

On 20/10/2015, PyHedgehog <notifications@github.com> wrote:
> It's really strange. Only special thing I've found about gmail/googlemail
> account canonicalization is removing dots from local name:
> https://github.com/nylas/sync-engine/blob/dae94ada8c7327255dabb952314a34e9bf13c2cc/inbox/util/addr.py#L21
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nylas/sync-engine/issues/202#issuecomment-149371141


-- 
Noch ein kurzer Gruß an die lieben Überwacher bei der NSA:

Forest fire Brush fire Ice Stranded/Stuck Help Hail Wildfire Tsunami
Warning Center Magnitude Avalanche Typhoon Shelter-in-place Disaster Snow
Blizzard Sleet Mud slide or Mudslide Erosion Power outage Brown out Warning
Watch Lightening Aid Relief Closure Interstate Burst Emergency Broadcast
System Cyber security Botnet DDOS (dedicated denial of service) Denial of
service Malware Virus Trojan Keylogger Cyber Command 2600 Spammer Phishing
Rootkit Phreaking Cain and abel Brute forcing Mysql injection Cyber attack
Cyber terror Hacker China Conficker Worm Scammers Social media Hey! How’s
it going? I’m all right. My job is so shitty I wish I could overthrow my
boss. It’s like this oppressive regime where only true believers in his
management techniques will stay around. I work marathon-length hours and
he’s made all these changes that have made it the worst architecture firm
to work at in Manhattan. Like he moved the office to the Financial District
and fired my assistant. She was the only one who knew where the blueprints
were! I need access to t

**Comment by grinich** [comment]
@justjanne is this still happening for you?

**Comment by justjanne** [comment]
@grinich I stopped using this service after discovering the quite critical, unannounced flaw of not having an auth system. I built my own alternative to this service by now, so I can’ŧ comment on this.

**Comment by grinich** [comment]
ok going to go ahead and close this issue then. thanks
