### ISSUE TITLE
exchange opensource ?

### ISSUE THREAD

**Issue by saqebakhter** [nylas/sync-engine#203]
any plans on adding exchange to the open source version of sync-engine ?

**Comment by spang** [comment]
We don't currently have plans to open source the Exchange support.

**Comment by joerocklin** [comment]
As a note: there are organizations who (largely for internal policy reasons) won't allow off-network access to the exchange servers. Since I didn't see the option for an on-premises version of the product on the main web site, does that mean the only option to have sync engine interface with exchange is to use the hosted product?

**Comment by saqebakhter** [comment]
Looks like it

Most companies will not allow there emails to be stored off premise so
exchange on the hosted sync engine would limit a lot of people

**Comment by grinich** [comment]
@saqebakhter currently, yes. We're investigating on-prem solutions, but we're mostly focused on just scaling the current service since there are already a ton of users.

**Comment by rghv** [comment]
@grinich is it a completely on-prem Nylas installation which you are referring to? Or just an agent/client that would interface with mailboxes on-prem MS Exchanges, which would connect to Nylas cloud? Just curious!

My use-case: Am building a simple monitoring system, which would be over an inbox. The system would keep polling (or be evented, via event hooks) a mailbox (which I plan to sync using Nylas) and then trigger subsequent events (based on certain logic) upon receiving a mail with certain preset subject/body. Only thing, this particular inbox is resident on an on-premise MS exchange server. Can I employ Nylas for this use-case? If this feature isn't in the open source edition of sync-engine, is there a paid subscription/licensed addon or something?

**Comment by grinich** [comment]
Either-- we're not sure what the best solution would be. Running infrastructure like the sync engine turns out to be pretty complicated, and we'd like to provide a great solution for IT managers.
