### ISSUE TITLE
/accounts is world-readable by default, allows login as user

### ISSUE THREAD

**Issue by justjanne** [nylas/sync-engine#205]
This issue should be considered a security issue:

/accounts is world-readable by default with no authentication and transmits information that can be used to login as any user. This has abuse-potential.

One possible fix:

Disable the /accounts endpoint and serve the information via a CLI tool.

**Comment by spang** [comment]
The open source sync engine is not meant to be run on the public Internet without proxying behind some sort of authentication service. You'll want to run it behind a VPN or on a local machine.
