### ISSUE TITLE
add config to limit the sync to the past week (or some duration)

### ISSUE THREAD

**Issue by jaredly** [nylas/sync-engine#208]
I'd like to try nylas, but syncing has gone on four ~10 hours, and has only gotten messages from the past month. My gmail messages go back years, so I'd rather be able to limit the syncing.

**Comment by spang** [comment]
How many gigs of email do you have? How many messages from the last month? Is there anything interesting in the logs it's outputting?

If you have a lot of mail it may take a while to sync all of it, but for typical use cases I'd imagine *much* more mail than a month of history to be downloaded in 10 hours, unless you're bandwidth limited.

**Comment by spang** [comment]
Please reopen this issue if you're still having problems! Without more information, we can't actually help. :)
