### ISSUE TITLE
Folder prefix

### ISSUE THREAD

**Issue by ricklupton** [nylas/sync-engine#210]
With my Fastmail account, all the folders show up in the sidebar as "INBOX.FolderA", "INBOX.FolderB" etc. Can this prefix be removed in the UI?

**Comment by khamidou** [comment]
Hi @ricklupton. 

Thanks for the bug report! Unfortunately, this is the wrong repository --- the sync engine is the backend app which powers N1. Since this is an UI issue, could you open it in the [N1 repository](https://github.com/nylas/N1)? 

regards,

Karim

**Comment by ricklupton** [comment]
Ah, sorry!

**Comment by khamidou** [comment]
It's okay!
