### ISSUE TITLE
Unable to Select Install Location

### ISSUE THREAD

**Issue by buecker** [nylas/sync-engine#224]
Auto-installing creates simplicity but makes it difficult for those of us who have a full c drive.  I didn't see a way to choose a different install location.

**Comment by khamidou** [comment]
Hi @buecker. Is this an issue about [nylas/N1](https://github.com/nylas/N1)? This repo contains the code for the sync-engine, the backend service which powers N1.

**Comment by buecker** [comment]
Yes, I did post in the wrong place.
