### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by chevdor** [nylas/sync-engine#226]
Context menu button to switch between accounts is barely visible
![image](https://cloud.githubusercontent.com/assets/738724/10993069/4ac67db2-846c-11e5-810f-9c1a0359a82a.png)

**Comment by khamidou** [comment]
Hi @chevdor. Thanks for taking the time to fill out this issue! Unfortunately, this is repo is about the sync-engine, the backend which powers [Nylas/N1](https://github.com/nylas/N1). You'd need to fill out this issue there.

regards,

Karim

**Comment by chevdor** [comment]
Sorry about that @khamidou 
Thanks for pointing out the right repo. I must admit I reported the issue kinda in the rush...
I filled the issue as https://github.com/nylas/N1/issues/382

**Comment by khamidou** [comment]
Don't worry, it's okay! Thanks for taking the time to fill again in the N1 repo!
