### ISSUE TITLE
Command failed with error code 1 in /vagrant

### ISSUE THREAD

**Issue by MitjaBezensek** [nylas/sync-engine#231]
Just tried to get the sync engine to work but faced this issue after vagrant up:
> ==> default: Command "/usr/bin/python -c "import setuptools, tokenize; __file__='/vagrant/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /vagrant
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by grinich** [comment]
Going to close this as stale. Please re-open if you continue to have the issue.
