### ISSUE TITLE
Documentation: ability to deploy sync-engine instances without full virtualization?

### ISSUE THREAD

**Issue by lkraav** [nylas/sync-engine#236]
https://github.com/nylas/sync-engine#installation-and-setup seems to have a rather heavy-handed approach. Is `virtualenv` not possible? I think I've gone through all available documentation and I can't really figure out what it takes to configure a multi-user setup to centralize an N1 experience across a single company. Let's say the company has 20 employees - does that mean 20 instances of VirtualBox running or...?

**Comment by khamidou** [comment]
Hi @lkraav,

Thanks for taking the time to file a ticket. The documentation isn't super explicit about setting up a multi-user server, but the gist is that you'll need to install a single instance of the sync-engine on a single server and then add multiple accounts to it (i.e: run in succession `bin/inbox-auth user1@email.com`, `bin/inbox-auth user2@email.com`, etc.). There's no need to have multiple servers or virtualenvs running.

Hope this made things clearer,

Karim

**Comment by lkraav** [comment]
Thanks. I sort of figured as much wrt multiple users. You didn't say anything about needing or not needing a fully virtualized environment. Is it safe to assume that there isn't any extra dark setup magic in that vagrant recipe and just running `setup.sh` will work anywhere?

**Comment by khamidou** [comment]
Yes, `setup.sh` should work on any Debian/Ubuntu server, whether it is virtualized or not.

**Comment by lkraav** [comment]
> Yes, setup.sh should work on any Debian/Ubuntu server, whether it is virtualized or not.

I am Gentoo. Care for my upcoming experience notes here?

**Comment by khamidou** [comment]
Oh, this definitely won't work then. `setup.sh` requires a Debian-based distribution. You'll have to make substantial changes to it to get it to install the right Python and MySQL versions.

**Comment by lkraav** [comment]
> Oh, this definitely won't work then. setup.sh requires a Debian-based distribution. You'd have to make substantial changes to it to get it to install the right Python and MySQL versions.

Indeed. Doesn't seem to be a big deal though. I'm pretty sure an `ebuild` can be created that takes care of the external dependencies. I already have most of it installed for other stuff, so let's see what happens.

I did just run `python setup.py install` in a fresh `virtualenv`. That dependency list length is crazy :), but aside from that here's a couple of notes:

1. should the docs say this is `python2` software? `vobject` for one doesn't seem to be `python3` compatible.

2.  `ipython>=1.0.0` will currently pull in `ipython-4.0.1`, which failed to build on my system. Restricting the requirement to `ipython==3.2.1` worked better. See the log below.

```
Installed /secure/home/nylas/lib/python2.7/site-packages/inbox_sync-0.4-py2.7.egg
Processing dependencies for inbox-sync==0.4
Searching for ipython>=1.0.0
Reading https://pypi.python.org/simple/ipython/
Best match: ipython 4.0.1
Downloading https://pypi.python.org/packages/source/i/ipython/ipython-4.0.1.zip#md5=274fe8b87d9c1a5816579933f0825c66
Processing ipython-4.0.1.zip
Writing /tmp/easy_install-KLFZBM/ipython-4.0.1/setup.cfg
Running ipython-4.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-KLFZBM/ipython-4.0.1/egg-dist-tmp-nVhUJD
error: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "darwin" and platform_python_implementation == "CPython"
```

**Comment by lkraav** [comment]
`setup.py` is also missing `faulthandler==2.3` dependency. What's the reason for `requirements.txt` and `setup.py` being out of sync? There's also a discrepancy regarding `imapclient`.

I figured it's actually a better idea to do `python setup.py develop`, because I am probably not going to change this system's time to UTC regardless of the warning. At least for this initial test run.

`inbox-start` has successfully started though. Gotta go configure MySQL access properly now.

**Comment by lkraav** [comment]
`inbox/ignition.py` needs help in `build_uri()`. I need to specify `...&unix_socket=/run/mysql/mysqld.sock` for the database connection to succeed. Not seeing this as configurable anywhere thus far.

**Comment by lkraav** [comment]
I also had to add `--binlog-format=MIXED` to my MariaDB execution. Otherwise the following error appeared with `bin/create-db`:

```
...
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1665, 'Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.') [SQL: u"INSERT INTO alembic_version (version_num) VALUES ('31aae1ecb374')"]
```
