### ISSUE TITLE
Dependencies in readme.md

### ISSUE THREAD

**Issue by Bugsbane** [nylas/sync-engine#238]
Please list the hard dependencies on the readme.md so it's easy to tell if a server will handle it, or if you require anything the sysadmin wouldn't be willing to install. Are virtualbox and vagrant really absolutely necessary for Sync-Engine to function? Is it suitable for shared hosting?

Thanks

**Comment by grinich** [comment]
Hi @Bugsbane -- VirtualBox and Vagrant are just tools to manage virtual machines. Most developers already have this installed, and it's the preferred way to use the sync engine to enforce isolation. This setup is designed for development flexibility. We don't recommend running it in production without adding additional authentication and security layers.

You can see the full list of installation dependencies in [setup.sh](https://github.com/nylas/sync-engine/blob/master/setup.sh).
