### ISSUE TITLE
Exception AttributeError: "'Lock' object has no attribute 'handle'"

### ISSUE THREAD

**Issue by lkraav** [nylas/sync-engine#240]
`inbox-start` startup is all successful, but sync never kicks off because this endlessly repeats:

```
[INFO] {"account_id": 1, "level": "info", "timestamp": "2015-12-09T22:53:36.152356Z", "module": "inbox.mailsync.service:164", "cpu_id": 0, "greenlet_id": 139850686733520, "email_address": "leho@domain.com", "event": "starting sync"}
[ERROR] {"account_id": 1, "level": "error", "timestamp": "2015-12-09T22:53:36.153034Z", "module": "inbox.mailsync.service:215", "cpu_id": 0, "greenlet_id": 139850686733520, "message": "", "event": "sync_error"}
Exception AttributeError: "'Lock' object has no attribute 'handle'" in <bound method Lock.__del__ of <inbox.util.file.Lock object at 0x7f3178532790>> ignored
```

This is part of #236 so a non-standard installation. OTOH everything looks healthy and working in this `virtualenv`. Any pointers on where to look for more details to debug further or how to best get a better stack trace here are welcome.

**Comment by grinich** [comment]
Hm, I've never quite seen that before. What are the details of the OS you're trying to run this on?

**Comment by lkraav** [comment]
Gentoo. Not doing any weird stuff, this is a production machine handling a bunch of apps without issues.

**Comment by grinich** [comment]
@emfree or @kav-ya  probably know more about how this locking works

**Comment by grinich** [comment]
i'm going to close this since we only currently support running the sync engine under ubuntu precise. thanks for your understanding
