### ISSUE TITLE
Document how to run on a server

### ISSUE THREAD

**Issue by wizonesolutions** [nylas/sync-engine#242]
The default sync engine adds everyone to an email list, and so it's likely people (like me) will come here and wonder how to run their own instance of the Sync Engine on a server.

What are the system requirements for such a server, and how does one configure the Sync Engine? In other issue you mentioned needing to think about authentication and security; how would one do that in practice (the stuff that is specific to the application)?

**Comment by grinich** [comment]
Hi @wizonesolutions -- It's documented in the [Readme[(https://github.com/nylas/sync-engine/blob/master/README.md) for how to run in a VM. You can also install on any debian-based system.

You need to provide some level of firewall or access control to limit 3rd-parties from being able to access your mailbox. For the hosted Nylas platform, we do this using a custom OAuth solution that vends access tokens and restricts by accounts/namespaces.
