### ISSUE TITLE
syncing via exchange difficulty

### ISSUE THREAD

**Issue by drcjcarr** [nylas/sync-engine#244]
I am having difficulty syncing with my work exchange server. It says that it connected successfully but cannot sync. my exchange server thinks that it is trying to sync from a mobile device and it blocks that access.  Cloudmagic allows my account to sync but not Nylas. What do I need to do to get this fixed? Seems there needs to be a way to make the access not appear to be coming from an iphone. Thanks!

Here is what I get in my email account when I try to sync:

Your phone won't be able to synchronize with the server via Exchange ActiveSync because of an access policy defined on the server.

Your device is currently in temporary quarantine.
If you are enrolling your device with MaaS360, this is a normal part of the activation process. Your device will be released from quarantine after final review by the Business Applications Team.
If have not recently enrolled your device with MaaS360, you must request an enrollment to be released from quarantine.

Information about your mobile phone:
Device model: iPhone
Device type: iPhone
Device ID: 22a0e6979d11447fb539f60d6e1ed7ca
Device OS:

Device user agent: python-EAS-Client 1.0
Device IMEI:

Exchange ActiveSync version: 14.0
Device access state: Blocked
Device access state reason: Individual

**Comment by grinich** [comment]
Hi @drcjcarr -- We use ActiveSync with the cloud Sync Engine. You likely will need to have your administrator allow access via MaaS360. Thanks.
