### ISSUE TITLE
Misleading documentation on updating labels in threads

### ISSUE THREAD

**Issue by masylum** [nylas/sync-engine#246]
https://nylas.com/docs/platform/#moving_folders

This part of the documentation is misleading and never was mentioned the non-rest `label/folder_ids` semantics.

I spent 20 minutes trying to figure out why sending `labels` was not working (I would have like that!) and I guess others stumbled in the same issue.

**Comment by grinich** [comment]
@masylum do you mean sending `labels` vs sending `label_ids`?

**Comment by masylum** [comment]
Yes. It's properly explained in messages but not in threads.

**Comment by grinich** [comment]
Updated: https://nylas.com/docs#threads

**Comment by masylum** [comment]
Thanks!
