### ISSUE TITLE
Support sqlite3 in addition to mysql

### ISSUE THREAD

**Issue by MisterTea** [nylas/sync-engine#251]
Mysql is great for enterprise, but for a single user that wants to run sync engine and N1 on their desktop, it isn't practical to install mysql.  I tried to fork the project and replace mysql with sqlite3.  I believe there's an issue because sqlite only has one connection, so api requests are not able to access the DB.

Here's the current state of things: https://github.com/MisterTea/sync-engine/tree/sqlite3

**Comment by grinich** [comment]
Realistically we're not going to merge this into mainline since it diverges so dramatically from the rest of our goals.
