### ISSUE TITLE
bin/inbox-start error line 2

### ISSUE THREAD

**Issue by StevenLemonier** [nylas/sync-engine#252]
bin/inbox-start failed with below error :
Traceback (most recent call last):
  File "bin/inbox-start", line 2, in <module>
    from gevent import monkey
ImportError: No module named gevent

**Comment by khamidou** [comment]
Hi @StevenLemonier,

It looks like `gevent` isn't installed. Did you run `setup.sh`?

regards,

k

**Comment by StevenLemonier** [comment]
Ok, it was not present in https://github.com/nylas/sync-engine#installation-and-setup

I ran postinstal.sh then setup.sh and it was fine.
Maybe you should add this steps to the instructions

**Comment by nodje** [comment]
:+1:
