### ISSUE TITLE
vagrant up: The guest machine entered an invalid state

### ISSUE THREAD

**Issue by Envo** [nylas/sync-engine#254]
Can't run sync-engine under OS X 10.11.

Vagrant says:

> The guest machine entered an invalid state while waiting for it
> to boot. Valid states are 'starting, running'. The machine is in the
> 'poweroff' state. Please verify everything is configured
> properly and try again.
> 
> If the provider you're using has a GUI that comes with it,
> it is often helpful to open that and watch the machine, since the
> GUI often has more helpful error messages than Vagrant can retrieve.
> For example, if you're using VirtualBox, run `vagrant up` while the
> VirtualBox GUI is open.
> 
> The primary issue for this error is that the provider you're using
> is not properly configured. This is very rarely a Vagrant issue.

And VirtualBox 5.0.14 says:

> Failed to load R0 module /Applications/VirtualBox.app/Contents/MacOS/VMMR0.r0: The owner is not >root: '/Applications' (VERR_SUPLIB_OWNER_NOT_ROOT).
> Failed to load VMMR0.r0 (VERR_SUPLIB_OWNER_NOT_ROOT).
> 
> Result Code: 
> NS_ERROR_FAILURE (0x80004005)
> Component: 
> ConsoleWrap
> Interface: 
> IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

What am i doing wrong?

**Comment by kevinr** [comment]
I'm going to guess that your installation of VirtualBox is screwed up somehow.  What does `ls -l /Applications/VirtualBox.app/Contents/MacOS/VMMR0.r0` say?

I'd try uninstalling and reinstalling VirtualBox and see if that fixes the problem.

**Comment by Envo** [comment]
> -rw-r--r--@ 1 root  admin  1753784 Jan 19 18:01 /Applications/VirtualBox.app/Contents/MacOS/VMMR0.r0

I tried to reinstall many times, nothing changed...

**Comment by Envo** [comment]
Any update on this?

**Comment by sakbhatn** [comment]
I had the same issue, replaced my previous VirtualBox snapshot as current. Also, changed Applications folder ownership to root:admin and it worked.

**Comment by thsowers** [comment]
Getting the same issue on Ubuntu 15.10, tried reinstalling sync engine, reinstalling virtual box etc but haven't had any success

**Comment by spang** [comment]
Folks, this looks like an issue with virtualbox rather than the sync engine. We're not sure what's going on for you but it's outside the scope of what we're willing to spend time looking into.
