### ISSUE TITLE
exchange support

### ISSUE THREAD

**Issue by sakoula** [nylas/sync-engine#259]
Hi,

I work for a company that hosts email in an exchange server (secured behind firewalls etc) exposing only Exchange protocols for the capable clients , SMTP (for sending mail) and POP3 (no IMAP). 

I would really love!!!!! to try nylas but cannot due to the fact that the opensource engine does not provide POP3 or exchange. Is there a slight chance that either of these protocols to be included in the open source sync-engine version?

Thanks!!!!!

**Comment by bherila** [comment]
+1, why is Exchange not available in this source tree?

**Comment by jeremyFreeAgent** [comment]
duplicate of #253

**Comment by khamidou** [comment]
Unfortunately, we don't have plans to open source Exhange syncing at the moment.

**Comment by LeeSaferite** [comment]
I know you have no obligation, but is there any chance you could explain the reasoning behind the decision to exclude the exchange portion?
