### ISSUE TITLE
vagrant up: got multiple errors, multiple times

### ISSUE THREAD

**Issue by avioli** [nylas/sync-engine#260]
Followed [installation-and-setup](https://github.com/nylas/sync-engine#installation-and-setup) but got the following errors (gists):
[vagrant up](https://gist.github.com/avioli/16676d4193a5ffabb7af)
[vagrant provision](https://gist.github.com/avioli/32ba6179a8c3c5fcce74)
[vagrant provision](https://gist.github.com/avioli/c96fe73709a99dea7b26)

In essence the first try gave up with `OpenPGP`, then the second try failed installing `pip`, then at the third try got past `pip` (not sure how), but got multiple SSLContext warnings and finally failed installing `ipython`.

I'm guessing provisioning should cleanup before staring.

I'll destroy the box and go from scratch once again.

**Comment by avioli** [comment]
The second try got past `OpenPGP`, `pip`, and `ipython`, but failed after `boto3` - `Read timed out`.

**Comment by grinich** [comment]
Closing due to stale and can't reproduce.
