### ISSUE TITLE
Newly received email has thread collapsed

### ISSUE THREAD

**Issue by orky** [nylas/sync-engine#263]
Upon receiving new email, it shows up in the inbox but does not allow me to view the content. If I click on the "..." it displays the content but makes it seems as though it was quoted, which is incorrect.
<img width="1177" alt="screen shot 2016-02-10 at 12 08 32 pm" src="https://cloud.githubusercontent.com/assets/1643567/12960269/34e9104e-cfef-11e5-857f-5710aa88ef47.png">

**Comment by bengotow** [comment]
Hi @orky —it sounds like this is an issue specific to the https://github.com/nylas/N1 mail client. I /think/ there's an issue for this over in that repository and it's being worked on this week. Cheers!
