### ISSUE TITLE
Support for Multiple Inboxes

### ISSUE THREAD

**Issue by orky** [nylas/sync-engine#265]
Like the Gmail Lab feature, it would be great to customize the default GUI. Ideally we could tile different parts of the interface into certain inboxes/labels/etc. to take advantage of all that real estate especially on higher resolutions & bigger screens. It would greatly increase the ways to use Nylas and put it ahead of existing mail clients out there.

**Comment by spang** [comment]
Hi there,

This is the bugtracker for the cloud sync that powers N1, not the GUI. Can you please check https://github.com/nylas/n1/issues to see if your suggestion exists there, and resubmit if not?

Thanks!
