### ISSUE TITLE
Thread snippets should replace newlines with spaces, not remove them.

### ISSUE THREAD

**Issue by bengotow** [nylas/sync-engine#266]
Email looks like:
![image](https://cloud.githubusercontent.com/assets/547354/13058045/302b85fc-d3d5-11e5-918d-4d382a062832.png)

Nylas inbox
![image](https://cloud.githubusercontent.com/assets/547354/13058061/4ae90de2-d3d5-11e5-8a74-27489897e662.png)

Gmail adds the spaces
![image](https://cloud.githubusercontent.com/assets/547354/13058068/5cad641a-d3d5-11e5-9f5e-1317b5d6737c.png)

Was originally https://github.com/nylas/N1/issues/1340

**Comment by emfree** [comment]
Should be fixed in 0a9286a77564c.
