### ISSUE TITLE
gevent dependency too old on Debian 8 (jessie) (should update to 1.0.2)

### ISSUE THREAD

**Issue by tbelliard** [nylas/sync-engine#267]
The currently defined gevent dependency specifies version 1.0.1, which is broken on Debian 8 (jessie) due to the full removal of SSLv3 protocol at library level.
See https://github.com/gevent/gevent/issues/513

Updating the file requirements.txt to reference version 1.0.2 instead of 1.0.1 resolves the problem.
I haven't tested enough at the moment to make sure that this update doesn't break anything, but considering it is a minor update it should be fairly safe.

**Comment by singhkay** [comment]
@tbelliard  Fixed in #295

**Comment by spang** [comment]
Fixed in latest release.
