### ISSUE TITLE
How to use Sync-Engine with hosted email server (Kolab)

### ISSUE THREAD

**Issue by wisemonkey** [nylas/sync-engine#269]
Can someone point steps to use Sync-Engine with hosted email server?
readme.md doesn't seem to go over the points when email server is not gmail, IMAP and SMTP server configs report errors.
I'm guessing `auth` needs to run before `start` (no need to start `api`), is that correct?
Once started I can simply go to client for remaining configuration and add `~/.nylas/config.cson`, is that correct?

**Comment by grinich** [comment]
What errors are being reported?

**Comment by wisemonkey** [comment]
I'm sorry got side tracked, I'll reproduce this and report back (hopefully in a day)

**Comment by wisemonkey** [comment]
Just an update:
Hosted version of N1 can work with SMTP (port 25), can't work with port 465. Shows up error: Check SMTP setup

sync-engine doesn't work with any port (25/465).
My username for SMTP relay service is different than my email address however `bin/inbox-auth` still shows up password for email (not sure if that is an issue)

```
SMTP username (empty for same as email address): <username>
SMTP password for <firstname.lastname@e-mail.com> (empty for same as IMAP):
```

**Comment by damianmoore** [comment]
For anyone stumbling across this in the search for how to configure their own server, this document is fairly helpful: https://github.com/nylas/N1/blob/master/CONFIGURATION.md

**Comment by grinich** [comment]
Closing due to stale and can't reproduce. Try the latest Nylas Mail release!
