### ISSUE TITLE
Where in inbox-sync command

### ISSUE THREAD

**Issue by mandarvaze** [nylas/sync-engine#276]
Documentation refers to ``inbox-sync stop``, but I could not find it under ``bin`` folder where rest of the commands like ``inbox-start`` and `inbox-auth`` ect. reside.

**Comment by grinich** [comment]
Docs are wrong at the moment. I believe you should use [`bin/sync-start-stop`](https://github.com/nylas/sync-engine/blob/master/bin/start-stop-account) instead.

**Comment by throrin19** [comment]
404
