### ISSUE TITLE
When retrying to send email, sync-engine duplicates "Sent" mailbox message entries

### ISSUE THREAD

**Issue by sergiosgc** [nylas/sync-engine#278]
When testing a spam filter, I sent a message that will not be accepted by my mail server. The sync-engine behind nylas-n1 is repeatedly trying to send the message. For each attempt, there is a copy of the message on my "Sent" mailbox folder. This is obviously an error.

The SMTP server is returning a 5.7.1 error. I believe duplication of the behaviour is only dependent on having an SMTP server return 5.7.1.

I will not post logs including email addresses on a public forum, but contact me privately and I can send you my email server logs and info on my nylas account for you to debug on your end.

**Comment by grinich** [comment]
Closing due to stale and can't reproduce. Try the latest Nylas Mail release?
