### ISSUE TITLE
How to set up on VPS/Debian VM

### ISSUE THREAD

**Issue by Porco-Rosso** [nylas/sync-engine#282]
Hi, 
I want to deploy my own instance of the nylas sync-engine. How can I deploy it on a system different from the one from which the client will be running?

As I understand, If I follow the current instructions with my setup (within a Proxmox Debian VM) I should end up with two layers of virtualization. At that point the localhost only connection on port 5555 will no longer be exposed.
Is there a way to run the sync engine directly on a system such as stock debian?

**Comment by joostrijneveld** [comment]
You ended up closing your own issue. Did you resolve it?

**Comment by Porco-Rosso** [comment]
I closed the issue because it is essentially the same as what I explain here: 
https://github.com/nylas/sync-engine/issues/283
Never got it to work, so if you have any insight, please share!
