### ISSUE TITLE
sync-engine wrongly requires entire system timezone to be UTC

### ISSUE THREAD

**Issue by marshallmcmullen** [nylas/sync-engine#285]
The binaries in Nylas sync-engine all fail to start if the system timezone is not UTC. Specifically inbox-app and inbox-sync. It's not always practical to put the system clock in UTC as the server running the sync-engine may not be a dedicated server running only nylas and the other services running on that server may have conflicting requirements that prevent changing the timezone to UTC without breaking other applications. Another obvious use case is for those of us that want to run the open source local sync engine on our desktops. In that scenario, having the system time set to UTC is completely unacceptable since it breaks calendaring and timestamps on emails you send with the Nylas N1 email client, etc.

A simpler alternative to requiring the entire system time to be UTC is to instead set the timezone for the **process** only. For example, in inbox/util/startup.py, simply add:

os.environ['TZ'] = 'UTC'
time.tzset()

This has zero effect on the overall system itself and instead only affects the process while simultaneously ensuring all time based operations for that process believe the system time is UTC as required.

I've attached a patch which I'm using locally to achieve this effect.

[force_utc.patch.zip](https://github.com/nylas/sync-engine/files/167882/force_utc.patch.zip)

**Comment by Porco-Rosso** [comment]
Can you elaborate on the effect of having UTC set is? Will my emails sent differ in some way?

**Comment by marshallmcmullen** [comment]
If you are running both the backend sync engine as well as the frontend Nylas N1 client on the same machine, without this fix then things get really messed up. I don't recall if it was on the outgoing or incoming side, but I'm pretty sure it was on all my outgoing messages having the wrong timestamps on them. This was really confusing with people receiving my emails as it looked like they were all being sent 8 hours later than I sent them.

**Comment by khamidou** [comment]
Hi,

Thanks for the patch! However, I feel like this is out of the scope of this project --- if you want the sync-engine to be the only process using UTC, patch your init scripts for the sync engine.

Cheers,

k

**Comment by joostrijneveld** [comment]
Thanks for this patch! I was running into the exact same situation, i.e. there are other services on the same system that I'd prefer not to run in UTC. Changing the timezone [during startup](https://github.com/nylas/sync-engine/blob/master/inbox/util/startup.py#L34) seems to work.
