### ISSUE TITLE
'Vagrant up' script to automate sync-engine startup process

### ISSUE THREAD

**Issue by claudioeddy** [nylas/sync-engine#291]
I'm trying to run a script using the example from [Vagrantfile.local.example](https://github.com/nylas/sync-engine/blob/master/Vagrantfile.local.example).
But it doesn't seem to work. What I want to do is to put the server up as soon as I run **vagrant up**, so that the commands from [Nylas Sync Engine readme](https://github.com/nylas/sync-engine/blob/master/README.md) are run automatically.
To do that, I created a **Vagrantfile.local** file under sync-engine directory and added the following content just to test running commands after **vagrant ssh**:
```
$run_email` = <<SCRIPT
vagrant ssh -- -c 'cd /vagrant/; ls'
SCRIPT

VAGRANTFILE_API_VERSION = "2" unless defined? VAGRANTFILE_API_VERSION

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision :shell, :inline => $run_email, :run => "always"
end
```
**vagrant up** executes properly, but in the end it reports:
```
    default: Running: inline script
==> default: stdin: is not a tty
==> default: /tmp/vagrant-shell: line 1: vagrant: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
So, it turns out I'm lost :cry: . I've seen some solutions such as [this](http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html) for the stdin problem, but when I added the content to the [Vagrantfile](https://github.com/nylas/sync-engine/blob/master/Vagrantfile#L32) under sync-engine directory, just before the following line, I still get the same stdin error. As for the other error, I don't know what to do.
`config.vm.provision :shell, :inline => "apt-get update -q && cd /vagrant && ./setup.sh"`
Any clues on how I could do that? I would like to end up running the following commands sequence (with which I get my email running properly by executing them manually):
```
vagrant up
vagrant ssh
cd /vagrant
bin/inbox-start &
bin/inbox-api &
```
 Thanks in advance.
Additional information:

- sync-engine  version (last commit): a322d9a
- os info: Ubuntu 15.10
- ubuntu kernel version: 4.2.0-35-generic

**Comment by jerblack** [comment]
Here's what I ended up doing to get the server to start automatically.

 - Create 'start-server.sh' in the sync-engine folder

```bash
#! /bin/bash
screen -A -d -m -U /vagrant/bin/inbox-start
screen -A -d -m -U /vagrant/bin/inbox-api
```
 - Make sure you run ```chmod +x start-server.sh``` after creating the file.
 - Add the following line to the Vagrantfile after the "vagrant-rekey-ssh" security check. This was line 64 for me.

```ruby
config.vm.provision "shell", inline: "/bin/bash /vagrant/start-server.sh", run: "always", privileged: false
```

**Comment by khamidou** [comment]
This works but ideally, you should be using a process monitor like [supervisor](http://supervisord.org/) or [runit](http://smarden.org/runit/). If `bin/inbox-start` crashes, you'll have to restart it manually with your solution, while supervisor will make sure that it gets restarted.

Cheers,

k
