### ISSUE TITLE
EAS not supported

### ISSUE THREAD

**Issue by mpcabd** [nylas/sync-engine#292]
I read in #253 that the sync-engine supports EAS (Exchange/Active Sync) but when I try to use `bin/inbox-auth --provider eas my.corporate.email@corporate.org` I get that `Inbox does not support the email provider.` and apparently it's because the entry for `eas` in `inbox/providers.py` does not contain a `type`.

I read also on the README.md that this engine doesn't support Exchange, so does it support Exchange over Active Sync? Or is it that this version doesn't support any exchange at all?

Thanks.

**Comment by grinich** [comment]
The open source sync engine only supports IMAP. Our hosted version supports Exchange.

**Comment by mpcabd** [comment]
Thanks Michael, can you elaborate more on the reason? Is it a technical reason or merely to offer it as a paid service?

**Comment by grinich** [comment]
Both.
