### ISSUE TITLE
Can I run the sync engine in my cloud VM?

### ISSUE THREAD

**Issue by singhkay** [nylas/sync-engine#294]
Reading through the installation instructions (https://github.com/nylas/sync-engine/blob/master/README.md#installation-and-setup), I see that the guide talks about how to deploy this on a local virtual box VM. Is it possible to get the sync engine up and running in a cloud VM (specifically Azure in this case)?

**Comment by grinich** [comment]
Probably! We only really test this on Debian deploys, but I see no reason you couldn't set it up there.

Make sure that you secure the `/accounts` endpoint, as that's what serves access tokens in the open source version.

Going to close this bug, but feel free to hop into our community Slack room if you have other questions. :) 

slack-invite.nylas.com

**Comment by singhkay** [comment]
@grinich Will do! sent a request for invite
