### ISSUE TITLE
--reauth creates duplicate accounts

### ISSUE THREAD

**Issue by cirk0** [nylas/sync-engine#297]
Let's say the password for an imap account has been changed and we want to update the credentials in sync-engine. We use ./inbox-auth --reauth but it just generates a duplicate account in the database.

After re-authorization, I tried ./inbox-console -e emailaddress to mark the offending account as deleted because i realised it's not possible to update password so better get rid of it.
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

It's also not possible to delete the account directly from the database because of foreign key constraint failure.
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`inbox`.`message`, CONSTRAINT `message_ibfk_3` FOREIGN KEY (`reply_to_message_id`) REFERENCES `message` (`id`))

Update:

I've managed to mark the accounts without password using ./start-stop-account --softdelete but then ./delete-marked-accounts hangs with these outputs:
[INFO] {"level": "info", "timestamp": "2016-04-28T15:32:04.686346Z", "module": "**main**:34", "host": "localhost", "greenlet_id": 140082082897424, "event": "Spawning delete process for host"}
[INFO] {"level": "info", "timestamp": "2016-04-28T15:32:04.686600Z", "module": "**main**:34", "host": "127.0.0.1", "greenlet_id": 140082082897424, "event": "Spawning delete process for host"}

No errors caught in inbox monitors.

**Comment by cirk0** [comment]
I managed to delete the accounts without password using the combination of ./start-stop-account --softdetete and ./delete-account-data .

If it's supposed to be like that, feel free to close the Issue.

**Comment by Dilatorily** [comment]
I was wondering the same thing too. Unfortunately, `start-stop-account` was removed in commit d6ca16db7702696db111d7cab0241dbaa650eb43 with no obvious alternatives.

**Comment by elbamos** [comment]
+1

**Comment by elbamos** [comment]
Have either of you found a solution to this? @Dilatorily ?

**Comment by Dilatorily** [comment]
No. I still have duplicate accounts on the sync-engine.

**Comment by cirk0** [comment]
until there is no alternative to the "bitrotted" scripts, the easiest way is to revert the commit posted by @Dilatorily above.

**Comment by elbamos** [comment]
@cirk0 Do you have any advice on how to even revert?  I'm running the sync engine off of docker.  

This is kind-of a nutty amount of effort for the simple task of telling an email client that your email password has changed.

**Comment by cirk0** [comment]
not sure about docker, i'm running it on Debian so in my case i could just simply copy/paste the script and save it to /bin directory. I sort of tried to mimick the Nylas method, so building deb packages with dh-virtualenv on a temporary integration ec2 instance and install it on the target server. For continuous development and deployment it's best to fork the master/production branch and only commit changes that doesn't make it even harder to use the sync-engine in production environment. I think the principal here is; you have to work hard to make this open-source code behave similar to the paid for sync engine. I can't blame them for that, since that's how they make money and still they published the code for adventurous folks which I appreciate.

**Comment by ConorIA** [comment]
@elbamos, I just figured out how to work around this on docker using @cirk0's hints. 

Are you running the nhurel docker build? That's the one I am running, so this is how I solved it: 

With your docker images running, execute `$ docker exec -it nylassyncengine_sync-engine_1 bash`. Change the name of the image to whatever yours is called. You should now be in a root shell in your docker image. 

```
# cd /opt/sync-engine/bin
# curl https://raw.githubusercontent.com/nylas/sync-engine/f54666160b677eefe640f9efd527c2d0768846b7/bin/start-stop-account > start-stop-account
# chmod +x start-stop-account
```

You will need to figure out what account id number to feed to the script. It goes in the order that you added accounts. In my case my duplicate account was 3. Note that this is unrelated to the id that you get from the api.

```
# ./start-stop-account --stop --id 3 --softdelete 
# ./delete-account-data 3
```

Note, if you get the account id wrong and accidently mark a valid account for deletion, just use the same script as `./start-stop-account --start --id 1`.

**Comment by grinich** [comment]
now fixed with --reauth option

**Comment by alexanderadam** [comment]
@grinich what means 'now fixed'?
I just tried the `--reauth` option on `17.1.6` and it's still creating duplicates for me.
