### ISSUE TITLE
ERROR when inbox-start

### ISSUE THREAD

**Issue by bambita** [nylas/sync-engine#299]
Hello,

I have installed custom sync-engine on debian. I authorized one gmail account and started inbox.

I am getting following error

`[ERROR] {"exception": "Traceback (most recent call last):\n\t  File \"/home/pi/nylas/sync-engine/inbox/util/concurrency.py\", line 46, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/home/pi/nylas/sync-engine/inbox/mailsync/backends/imap/generic.py\", line 188, in _run_impl\n    self.state = self.state_handlers[old_state]()\n\t  File \"/home/pi/nylas/sync-engine/inbox/util/concurrency.py\", line 46, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/home/pi/nylas/sync-engine/inbox/mailsync/backends/imap/generic.py\", line 282, in initial_sync\n    self.initial_sync_impl(crispin_client)\n\t  File \"/home/pi/nylas/sync-engine/inbox/mailsync/backends/gmail.py\", line 271, in initial_sync_impl\n    self.batch_download_uids(crispin_client, uids, g_metadata)\n\t  File \"/home/pi/nylas/sync-engine/inbox/mailsync/backends/gmail.py\", line 464, in batch_download_uids\n    uid = expanded_pending_uids.next()\n\t  File \"/home/pi/nylas/sync-engine/inbox/mailsync/backends/gmail.py\", line 447, in expand_uids_to_download\n    uids = set(uids).union(crispin_client.expand_thread(g_thrid))\n\t  File \"/home/pi/nylas/sync-engine/inbox/crispin.py\", line 965, in expand_thread\n    self.conn.search(['X-GM-THRID', g_thrid])]\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 725, in search\n    return self._search(criteria, charset)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 747, in _search\n    args.extend(_normalise_search_criteria(criteria, charset))\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 1270, in _normalise_search_criteria\n    return [_handle_one_search_criteria(item, charset) for item in criteria]\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 1278, in _handle_one_search_criteria\n    return _maybe_quote(to_bytes(item, charset))\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 1291, in _maybe_quote\n    out = arg.replace(b'\\\\', b'\\\\\\\\')\n\tAttributeError: 'long' object has no attribute 'replace'\n", "account_id": 1, "level": "error", "timestamp": "2016-05-04T07:54:50.429434Z", "greenlet_id": 1896607376, "module": "inbox.util.concurrency:69", "state": "initial", "provider": "gmail", "folder": "[Gmail]/All Mail", "event": "Uncaught error"}
`

Any idea?

Please help. Thanks

**Comment by grinich** [comment]
Closing due to stale and can't reproduce.
