### ISSUE TITLE
sync-engine does not support outlook.com accounts 

### ISSUE THREAD

**Issue by brianmaher84** [nylas/sync-engine#301]
> Installation and Setup

> Install the latest versions of VirtualBox and Install Vagrant.

> git clone https://github.com/nylas/sync-engine.git

> cd sync-engine

> vagrant up

> Feel free to check out the Vagrantfile while this starts up. It creates a host-only network for the VM at > 192.168.10.200.

> vagrant ssh

> cd /vagrant

> bin/inbox-start

> And voilà! Auth an account via the commandline to start syncing:

> bin/inbox-auth ben.bitdiddle1861@gmail.com
> The inbox-auth command will walk you through the process of obtaining an authorization token from Google or another service for syncing your mail. In the open-source version of the sync engine, your credentials are stored to the local MySQL database for simplicity. The open-source Nylas Sync Engine does not support Exchange, but the hosted version does.

Replacing bin/inbox-auth ben.bitdiddle1861@gmail.com with an outlook address results in the error:

> raceback (most recent call last):
  File "bin/inbox-auth", line 66, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "bin/inbox-auth", line 51, in main
    auth_handler = handler_from_provider(provider)
  File "/vagrant/inbox/auth/base.py", line 39, in handler_from_provider
    raise NotSupportedError('Nylas does not support the email provider.')
inbox.basicauth.NotSupportedError: Nylas does not support the email provider.

Expected behavior is same as Gmail since this is outlook.com email address and not a Microsoft Exchange provider which I know is not supported in sync-engine.

**Comment by brim4brim** [comment]
It looks like there might be an outlook.py file missing from "inbox/auth/" directory.

There is a similar file here for gmail.py.

inbox/models/backends/gmail.py exists and a similar file exists for outlook:
inbox/models/backends/outlook.py

Since /inbox/auth/gmail.py heavily references this file, I would have expected a similar /inbox/auth/outlook.py doing the same.

**Comment by miedzinski** [comment]
Indeed it doesn't work on b261171446d727bdcbfeefb305f15add2c815679. It seems that it is possible to configure it as an IMAP account though. Apply patch below and run `/vagrant/bin/inbox-auth your@email`.

```
diff --git a/bin/inbox-auth b/bin/inbox-auth
index 51fb0e4..e347858 100755
--- a/bin/inbox-auth
+++ b/bin/inbox-auth
@@ -39,13 +39,14 @@ def main(email_address, reauth, target, provider):

         auth_info = {}

-        if not provider:
-            provider = provider_from_address(email_address)
+        #if not provider:
+        #    provider = provider_from_address(email_address)

-            # Resolve unknown providers into either custom IMAP or EAS.
-            if provider == 'unknown':
-                is_imap = raw_input('IMAP account? [Y/n] ').strip().lower() != 'n'
-                provider = 'custom' if is_imap else 'eas'
+        #    # Resolve unknown providers into either custom IMAP or EAS.
+        #    if provider == 'unknown':
+        #        is_imap = raw_input('IMAP account? [Y/n] ').strip().lower() != 'n'
+        #        provider = 'custom' if is_imap else 'eas'
+       provider = 'custom'

         auth_info['provider'] = provider
         auth_handler = handler_from_provider(provider)
```

`sync-engine` seems to do stuff with this account and doesn't throw any errors, but unfortunately I can not confirm it fully works because of https://github.com/nylas/N1/issues/2468.

**Comment by pfista** [comment]
Our hosted version of the sync engine supports syncing Exchange servers. Unfortunately, we don't have plans to open source the Exchange syncing code at the moment.

#259 #292
