### ISSUE TITLE
Local copies

### ISSUE THREAD

**Issue by surfatwork** [nylas/sync-engine#303]
HI,
just downloaded this yesterday and got a local sync-engine and N1 client up and running on Arch. Excellent stuff and good documentation! thanks. look forward to the calendaring front-ends.

I had a question - apologies if this is a newbie question. Would I be right in understanding that 
(i) the sync-engine downloads a local copy of my mail from the IMAP server into the VM
(ii) the N1 client then again stores a local copy of mail in .nylas
Does that mean 2 local copies of all my mail?

**Comment by khamidou** [comment]
Yes, you're correct. N1 was designed to work with the hosted sync engine, and we decided that keeping a copy locally made sense, mostly for speed and offline work reasons.
