### ISSUE TITLE
Changing a password?

### ISSUE THREAD

**Issue by elbamos** [nylas/sync-engine#306]
It doesn't seem that running the sync engine locally works with the N1 "update authorization" button.  This makes it (apparently) difficult (impossible?) to change an email password.

**Comment by spikenheimer** [comment]
you can use the bin/inbox-auth --reauth <emailaddress> to reauth an existing account

**Comment by elbamos** [comment]
Doing that appears to work, but N1 still reports that it can't connect to the account.  Its an icloud account, so maybe that has something to do with it. 

At the same time, I had tried to add two additional (gmail) accounts.  While the sync engine interface reports that they (and the icloud account) are 'running', they show up in N1 without any folders or email contents.

**Comment by elbamos** [comment]
Yeah - @spikenheimer  running inbox-auth doesn't reauthorize the account.  It creates a new account.  Now I have an extra, invalid, account.  But I also have two accounts that have the same username, which means that any API calls that ask for the username now fail.

**Comment by grinich** [comment]
Closing due to stale and can't reproduce. Try the latest build of Nylas Mail!
