### ISSUE TITLE
Windows Default Program > Missing

### ISSUE THREAD

**Issue by Maggew** [nylas/sync-engine#307]
Specifically, the "mailto:" is gone on Windows 8.1 Control Panel > Default Programs > Set Your Default Programs > Missing

I was surfing craigslist and when I clicked reply, it just wasn't possible to set default mailto: as Nylas.

**Comment by spikenheimer** [comment]
is this for the sync-engine or for https://github.com/nylas/N1 ?  it feels like it should be reopened on https://github.com/nylas/N1/issues

**Comment by khamidou** [comment]
Right, this is an N1 issue. @Maggew please re-open it here: https://github.com/nylas/n1/issues/.
