### ISSUE TITLE
Vagrant VM hangs during initial boot

### ISSUE THREAD

**Issue by verandaguy** [nylas/sync-engine#316]
I'm trying to set up the sync engine on a brand-new DigitalOcean box running Ubuntu 14.04, with VirtualBox 5.0 as a provider for Vagrant 1.8.4.

For some reason, the install hangs (even overnight) at `=> default: Booting VM`.

After a reboot, I tried to `VAGRANT_LOG=info vagrant up`, and I got the following relevant lines:

```
==> default: Running 'pre-boot' VM customizations...
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "modifyvm", "71d23a94-b52f-4d0e-92e8-2bdd817550c2", "--memory", "1024"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "modifyvm", "71d23a94-b52f-4d0e-92e8-2bdd817550c2", "--cpus", "2"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Boot:0x000000037ba068>
 INFO interface: info: Booting VM...
 INFO interface: info: ==> default: Booting VM...
==> default: Booting VM...
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "startvm", "71d23a94-b52f-4d0e-92e8-2bdd817550c2", "--type", "headless"]
 INFO subprocess: Command not in installer, restoring original environment...
```

The command `/usr/bin/VBoxManage` is available and executable on my host machine. This issue is present both when running as root as well as when running as a non-root user.

This command does leave some lingering `VBox*` processes, notably `VBoxHeadless`, which must be killed manually before trying to `vagrant up` again.

**Comment by verandaguy** [comment]
Update: this issue also exists on Debian 8.5 x64.

**Comment by verandaguy** [comment]
After some discussion on Slack, this issue was found to be caused by Vagrant, and is out of the scope of the sync-engine project.

**Comment by joaop** [comment]
how did you fix it ?

**Comment by verandaguy** [comment]
@joaop I never got this issue fixed. I have moved away from N1 since. Sorry about not replying sooner!

**Comment by converge** [comment]
I moved away too.
