### ISSUE TITLE
Error while loading config.json

### ISSUE THREAD

**Issue by foxtrot9** [nylas/sync-engine#318]
I have trying to get my own Nylas sync-engine running for Nylas N1 client.
But after configuring, config.json under instructions availabe at https://github.com/nylas/N1/blob/master/CONFIGURATION.md
I am getting this error.
![sync-engine](https://cloud.githubusercontent.com/assets/20148223/16780024/723f978a-4892-11e6-8b31-4e5ba19be80c.png)

**Comment by GabLeRoux** [comment]
I think I'm having same problem, see #319

**Comment by foxtrot9** [comment]
@GabLeRoux did you found any solution?

**Comment by jonasws** [comment]
I had this issue, and submitted a PR, that has been merged: https://github.com/nylas/N1/pull/2485
