### ISSUE TITLE
Cannot get passed the Onboarding modal when using my own sync-engine

### ISSUE THREAD

**Issue by GabLeRoux** [nylas/sync-engine#319]
```
Could not reach http://localhost:5009/onboarding?utm_medium=N1&utm_source=OnboardingPage. The server closed the connection without sending any data.
```

![image](https://cloud.githubusercontent.com/assets/1264761/16790744/50e177f4-4886-11e6-9858-e569f64d5a65.png)

I followed the steps described in https://github.com/nylas/N1/blob/master/CONFIGURATION.md and everything seems to work as expected until I open Nylas N1 client (version `0.4.45-7637265`). 

I grabbed latest code from sync-engine vagrant, and everything went smoothly. I also moved my `~/.nylas` to somewhere else so I could start cleanly. My config is the same as in CONFIGURATION.md, here's a sample with sensitive data removed:

```
{
  "*": {
    "env": "local",
    "nylas": {
      "accounts": [
        {
          "account_id": "<snip>",
          "email_address": "lebreton.gabriel@gmail.com",
          "id": "<snip>",
          "name": "Gabriel Le Breton",
          "object": "account",
          "organization_unit": "label",
          "provider": "gmail"
        }
      ],
      "accountTokens": {
        "<snip>": "<snip>"
      },
      "threadCountsValid": true
    },
    "core": {
      "disabledPackages": [
        "message-view-on-github",
        "personal-level-indicators",
        "phishing-detection",
        "github-contact-card",
        "keybase"
      ],
      "disabledPackagesInitialized": true
    },
    "threadSearchIndexVersion": 1
  }
}
```

When I open Nylas, it promps me with the welcome back message:

![image](https://cloud.githubusercontent.com/assets/1264761/16790732/40f2035e-4886-11e6-9ca1-f58f0951b2f9.png)

Then I hit next a few times until I reach this:

![image](https://cloud.githubusercontent.com/assets/1264761/16790744/50e177f4-4886-11e6-9858-e569f64d5a65.png)

My 5009 is grabbed by nylas vm:

```
 sudo netstat -peanut | grep 5009
[sudo] password for gableroux: 
tcp        0      0 127.0.0.1:5009          0.0.0.0:*               LISTEN      1000       24069570   21895/VBoxHeadless  
```

but `curl http://localhost:5009/onboarding?utm_medium=N1&utm_source=OnboardingPage` gives me "curl: (56) Recv failure: Connection reset by peer"

on vagrant:
```
sudo netstat -peanut | grep 5009
```
No result. Since it's specified in `nylas-sync`'s `VagrantFile`, I guess I have a missing service there on vagrant eh ;) Am-I missing something?

I ran nylas using `nylas --verbose` and didn't see anything.

**Comment by jonasws** [comment]
Fixed by https://github.com/nylas/N1/pull/2485, skipping the onboarding page
