### ISSUE TITLE
Update to Ubuntu Xenial 16.04 in progress?

### ISSUE THREAD

**Issue by COLABORATI** [nylas/sync-engine#372]
Hi , I have just seen that this project is still hanging on precise - are there any plans upgrading to Ubuntu Xenial 16.04?

**Comment by alexanderadam** [comment]
There is a [pull request from april](https://github.com/nylas/sync-engine/pull/295) that should handle these things.
However, nobody seems to care about it. 😞

**Comment by grinich** [comment]
We're not planning to upgrade right now as there's no direct benefit to our project goals.
