### ISSUE TITLE
Does not attempt to resync with account after imap outage

### ISSUE THREAD

**Issue by happydemic** [nylas/sync-engine#376]
**Version**: [f168287](https://github.com/nylas/sync-engine/commit/f168287017dbbda17c23e589768d1e6cbfe849bc)

**Bug**: sync engine does not attempt to reconnect to an IMAP server after an outage

**Detail**: After an IMAP account went down at the service provider end, the sync engine API accounts endpoint sensibly reported it as "sync_state": "invalid". The IMAP provider became available again a few hours later. Other IMAP clients (Thunderbird, iOS Mail etc.) were then able to connect to that account without difficulty. But the API continued to report sync_state invalid, and sync engine did not reconnect, including after a restart of bin/inbox-start. 

Investigation of the output of inbox-start suggested that the account with sync_state invalid was being ignored entirely. I used the deprecated start-stop-account script removed after [f546661](https://github.com/nylas/sync-engine/commit/f54666160b677eefe640f9efd527c2d0768846b7) to forcibly start the ignored account. Sync then returned to normal.

This is not the desired behaviour; I haven't checked the code, but presumably sync engine is supposed to retry at periodic intervals after getting sync_state invalid, and certainly it should retry after inbox-start is restarted.

As a secondary point, the documentation on manually starting or stopping an account needs updating. The README notes "The `inbox-sync` command allows you to manually stop or restart the sync by running `inbox-sync stop [YOUR_ACCOUNT]@example.com` or `inbox-sync start [YOUR_ACCOUNT]@example.com`", but I think that command stopped working in 2015.

**Comment by grinich** [comment]
Sync state invalid refers to having invalid credentials and login failing, and we don't keep retrying so we don't DDOS the server. This is a design goal . Most applications have a "retry" button in their application where they do this manually and set the sync state.
