### ISSUE TITLE
setup.sh AttributeError: 'module' object has no attribute 'Any'

### ISSUE THREAD

**Issue by cmoud94** [nylas/sync-engine#382]
Trying to get sync-engine up & running. But after running `vagrant up` for the first time I got this error.

```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py", line 14, in <module>
    from ndg.httpsclient.subj_alt_name import SubjectAltName
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 102, in <module>
    class AnotherName(univ.Sequence):
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 105, in AnotherName
    namedtype.NamedType('value', univ.Any().subtype(
AttributeError: 'module' object has no attribute 'Any'
```

Branch tried to build:
master

Latest commit:
[c5318cb32595ff208e8e43634cf89d3675836e7a](https://github.com/nylas/sync-engine/commit/c5318cb32595ff208e8e43634cf89d3675836e7a)

**Comment by krruzic** [comment]
Got this too. Install `pyasn1` with `easy_install` and it works.

Got the idea here: https://github.com/scrapy/scrapy/issues/783

**Comment by cmoud94** [comment]
@krruzic doesn't work, still got the (exactly) same traceback while running `sudo ./setup.py` after installing `pyasn1` as you suggested.

**Comment by Stephen-Chen** [comment]
Maybe this problem is the same to #383 .
I am waiting for the solution.

**Comment by mariusepi** [comment]
Apparently there's a stale component in the repositories of the pip version automatically installed by the script. I tried with Debian stable as a base for the virtual machine provisioned by vagrant (instead of Ubuntu) and all went fine. 
Changes in Vagrantfile that worked for me:
`config.vm.box = "debian/jessie64"`
Admittedly this is not a solution but just a workaround.

**Comment by Stephen-Chen** [comment]
@mariusepi Well,this solution don't work on me.
Anyway, thank you for your help.

**Comment by cmoud94** [comment]
@Stephen-Chen I've looked at your issue and you've got exactly the same traceback in the same part of setup as me. So I think you can delete it as it's quite redundant to report same thing twice.

Possible duplicate: [#383](https://github.com/nylas/sync-engine/issues/383)

**Comment by cmoud94** [comment]
@mariusepi Seems to work, at least the setup passed behind the part where it failed previously.

But there's another problem and that's missing required version of `setuptools`.
```
Collecting imapclient from git+https://github.com/nylas/imapclient.git@5ae2b9283aba024ed4b4dc3f826515e01ae2380b#egg=imapclient (from -r requirements.txt (line 63))
  Cloning https://github.com/nylas/imapclient.git (to 5ae2b9283aba024ed4b4dc3f826515e01ae2380b) to /tmp/pip-build-rsFPCZ/imapclient
  Could not find a tag or branch '5ae2b9283aba024ed4b4dc3f826515e01ae2380b', assuming commit.
    Complete output from command python setup.py egg_info:
    
    The required version of setuptools (>=18.2) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'easy_install -U setuptools'.
    
    (Currently using setuptools 5.5.1 (/usr/lib/python2.7/dist-packages))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 2 in /tmp/pip-build-rsFPCZ/imapclient/
```
I've fixed it, as suggested by install script, by running `sudo easy_install -U setuptools`. Setup has completed successfully with your workaround and manual installation of `setuptools`. Thanks for your advice.

**Comment by mamantoha** [comment]
This helps me. Thanks everyone!

```
sudo easy_install -U pyasn1 setuptools
```

**Comment by cmoud94** [comment]
@mamantoha Your suggestion helped me to get sync-engine up & running. Thanks a lot. I'm closing this issue now as it seems to be solved.
