### ISSUE TITLE
Number of Connection Sessions

### ISSUE THREAD

**Issue by atanasbozhkov** [nylas/sync-engine#394]
I have a Nylas Sync engine set up on my VPS. Several days ago I was contacted by the Support Team of VPS provider stating that my instance was killed because of a high numer of Conntrack Sessions (over 36,000).
Now provided the fact that I had only the Sync engine running - I am inclined to think that it might have been the reason for the high number of sessions.
I have manually limited the number of sessions for the OS, but I wanted to know whether this many sessions are a normal for the sync engine?

**Comment by grinich** [comment]
Closing due to stale and can't reproduce.
