### ISSUE TITLE
No Imap folder sync after a single folder sync failure

### ISSUE THREAD

**Issue by jcnoir** [nylas/sync-engine#396]
No more imap folder sync after a failure on a specific imap folder.

On a self hosted nylas sync engine (based on current master : 91e3a8bff6ef0656eca9e356c07963c8b238d876) I have an imap folder (a symlink) that the sync engine does not like : dovecot.sieve
This is a folder where I store my user sieve rules to automatically sort mails in the right folder.
This folder causes the following error in the log :

``` json
{"account_id": 1, "timestamp": "2016-09-11T08:30:57.654822Z", "module": "inbox.crispin:239", "greenlet_id": 139849459476912, "event": "Connection broken with error; retrying with new connection", "exception": "Traceback (most recent call last):\n\t  File \"/opt/sync-engine/inbox/util/concurrency.py\", line 56, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/opt/sync-engine/inbox/mailsync/backends/imap/generic.py\", line 296, in initial_sync\n    crispin_client.select_folder(self.folder_name, uidvalidity_cb)\n\t  File \"/opt/sync-engine/inbox/crispin.py\", line 353, in select_folder\n    folder, readonly=self.readonly)\n\t  File \"/usr/lib/python2.7/site-packages/imapclient/imapclient.py\", line 489, in select_folder\n    self._command_and_check('select', self._normalise_folder(folder), readonly)\n\t  File \"/usr/lib/python2.7/site-packages/imapclient/imapclient.py\", line 1196, in _command_and_check\n    self._checkok(command, typ, data)\n\t  File \"/usr/lib/python2.7/site-packages/imapclient/imapclient.py\", line 1202, in _checkok\n    self._check_resp('OK', command, typ, data)\n\t  File \"/usr/lib/python2.7/site-packages/imapclient/imapclient.py\", line 1082, in _check_resp\n    raise self.Error(\"%s failed: %s\" % (command, to_unicode(data[0])))\n\terror: select failed: [SERVERBUG] Internal error occurred. Refer to server log for more information. [2016-09-11 08:30:57]\n", "level": "info", "state": "initial", "provider": "imap", "folder": "dovecot.sieve"}
```

I can work around the issue by moving this specific folder outside my imap folders.
But the real issue is that a single imap folder sync breaks all imap folders.
The INBOX keeps being updated but the other imap folders are not usable anymore. 
Sometimes some folders are synced, sometimes no folder is synced.

Please make a single imap folder crash do not break all other imap folders.

For information no reboot / database clean / redis clean changes the issue.

**Comment by grinich** [comment]
Closing due to stale and can't reproduce.
