### ISSUE TITLE
Run setup.sh gives error

### ISSUE THREAD

**Issue by markimarc** [nylas/sync-engine#399]
When i run `bash setup.sh`
I get an error reporting: 
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5WatyV/imapclient/`

**Comment by zbloss** [comment]
I am also getting this error
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-R3OggK/imapclient/

**Comment by zbloss** [comment]
I did get it working.

What this error means, is most likely you are missing a dependency. Run setup.sh and wait until it crashes and you get the egg_info error.

Look up about 5 lines of code and you should see what dependency you are missing.

This was a lot of trial and error on my end. I would run setup.sh, fix a dependency, run setup.sh, fix another dependency....
