### ISSUE TITLE
Support vagrant-lxc to install the sync-engine

### ISSUE THREAD

**Issue by elopio** [nylas/sync-engine#401]
I can't use virtualbox with vagrant because it has a conflict with my kvm setup. So I started looking at starting it using lxc. It's lightweight, which makes it perfect for my already busy machine.

Adding this to the Vagrantfile I could start and run it successfully:

```
config.vm.provider :lxc do |libvirt, override|
  override.vm.box = "fgrehm/precise64-lxc"
end
```

It's probably missing the memory and cpu limits, but I don't know how to do that in vagrant for the lxc provider.

**Comment by grinich** [comment]
Pull Requests / Forks welcome! We're not currently putting this on our roadmap though.

**Comment by elopio** [comment]
ack. If I get the time to learn more vagrant, I'll make a proper PR with the limits.

**Comment by grinich** [comment]
👍
