### ISSUE TITLE
Additional Dependences for Debian installation

### ISSUE THREAD

**Issue by kusius** [nylas/sync-engine#405]
Tried to install on Debian 8 today and needed to do the following manually, for the setup.sh to finish sucessfully: 
1. Needed to install `libssl-dev` for python cryptography to install correctly 
   `sudo apt-get install libssl-dev`
2. Needed the `cffi` module 
   `easy_install -U cffi`

I would suggest modifying the setup.sh script to account for those.  
Thank you!

**Comment by massimodong** [comment]
The latest version of cffi leaves an error for me.
But `1.2.1` works
`easy_install -U cffi==1.2.1`

**Comment by klaszlo** [comment]
libssl-dev was also required in ubuntu 16.04.1 LTS.

**Comment by grinich** [comment]
Closing due to stale and can't reproduce.
