### ISSUE TITLE
iso-2022-jp encoding emails not displaying correctly

### ISSUE THREAD

**Issue by bengotow** [nylas/sync-engine#408]
It's an S/MIME signed message and its content starts with

```
Content-Type: text/plain; charset="iso-2022-jp"
Content-Transfer-Encoding: 7bit
Here's what some of the text looks like
```

https://cloud.githubusercontent.com/assets/679224/19425465/b92a5dac-946d-11e6-97d5-9aa2048f7a1d.png

Can't provide more as it's a sensitive email.

**Comment by inket** [comment]
Seems to be fixed with the new version?

I received more emails with the same encoding & signing and they're showing up fine. Old emails are still garbled. Besides the Nylas update, I was also upgraded to the new Outlook, so maybe that's related.
