### ISSUE TITLE
Sent mail appears as unread mail in inbox - blocks genuine notification

### ISSUE THREAD

**Issue by tenleftfingers** [nylas/sync-engine#409]
I'm up-to-date with N1 0.4.59 and this issue is at least a year old.

From any account (gmail, zoho, ok.de), when I send a mail, the conversation is updated as being "unread" and appears in bold. The notification in the system tray goes blue.

This means when I do get email I have no way of knowing as the notification dot is always there.

I have to click away to another email thread and back to the one with the sent/unread to make it go away.

**Comment by grinich** [comment]
Try with the new Nylas Mail app?
