### ISSUE TITLE
use whole domain

### ISSUE THREAD

**Issue by dcrystalj** [nylas/sync-engine#415]
I have domain @example.com 

How can i reply using same as received emails from random addresses. Lets say i receive mail ```replyhere@example.com``` and i want to reply back using same ```replyhere@example.com``` domain. 
Later i receive mail to ```nylas@example.com``` and  i want to reply back using same ```nylas@example.com```.

tl;dr i want to have infinite mails for my domain

regards

**Comment by khamidou** [comment]
Hi @dcrystalj – you'd need to set up your mail server (Postfix or Qmail or any other) to have a catch-all email address. After that, you could use the sync-engine's built-in alias support to be able to send message as `replyhere@example.com` or `nylas@example.com`.
