### ISSUE TITLE
Office365 support?

### ISSUE THREAD

**Issue by ronilaukkarinen** [nylas/sync-engine#420]
Hello, I'm trying to setup sync-engine for 2 gmails and 1 office365 accounts. How to add Office365 email? don't know if this is right place to ask, but as it is directly related to sync-engine, decided to give github issue a go. Didn't find this in documentation. Thanks in advance.

**Comment by bherila** [comment]
Nylas did not open-source their implementation of the Exchange protocols.

**Comment by bherila** [comment]
Second thought: I guess as a workaround you could add the office365 account as an IMAP account.

**Comment by pfista** [comment]
That's correct, our open source sync engine doesn't support Exchange/ActiveSync, though you can try connecting it as an IMAP account like bherila suggested.
