### ISSUE TITLE
import config error

### ISSUE THREAD

**Issue by chakrihacker** [nylas/sync-engine#425]
I am using ubuntu 16.04 and my vagrantbox provision failed to run setup.sh so I ran it manually and I had couple of errors (installing setuptools and pyasn1) and now I am having import error

Traceback (most recent call last):
  File "bin/create-db", line 9, in <module>
    from inbox.config import config
ImportError: No module named config

**Comment by ronnietucker** [comment]
Same here.

`Finished installing dependencies.
Copying default development configuration to /etc/inboxapp
Copying default secrets configuration to /etc/inboxapp
Copying default mysql configuration to /etc/mysql/conf.d
2017-01-15T17:56:58.165185Z mysqld_safe Logging to syslog.
2017-01-15T17:56:58.169599Z mysqld_safe Logging to '/var/log/mysql/error.log'.
2017-01-15T17:56:58.221094Z mysqld_safe A mysqld process already exists
Traceback (most recent call last):
  File "bin/create-db", line 9, in <module>
    from inbox.config import config
ImportError: No module named config
`

**Comment by MooShoe** [comment]
+1

**Comment by ajcollett** [comment]
+1

**Comment by itsjef** [comment]
+1

how to I work through this?

**Comment by ronnietucker** [comment]
Still no luck with this, but it sounds like the new versions of Nylar won't need the sync engine.

**Comment by MooShoe** [comment]
yea i cant wait until nylas basic comes out on linux.

**Comment by itsjef** [comment]
There is a workaround at https://github.com/nylas/sync-engine/issues/427. Works for me :smile:

**Comment by chakrihacker** [comment]
Since We got workaround I am closing this issue
