### ISSUE TITLE
Yandex mail tags not present in Nylas

### ISSUE THREAD

**Issue by jeffmcneill** [nylas/sync-engine#426]
Yandex Mail has tags (similar to Google). However, when connecting (via IMAP) with Nylas, those mail tags are not present, only folders. Yandex Mail has an API, but there does not appear to be tag functionality with it. Would be great to put this on the roadmap as a new feature request. For now I need to go back to no tags and only folders, which is ok, but slower, if I want to use Nylas (which I do).

**Comment by grinich** [comment]
Unfortunately since they don't have an API, we won't be able to implement this. 😦
