### ISSUE TITLE
details about nylas cloud/sync-engine

### ISSUE THREAD

**Issue by cocodrino** [nylas/sync-engine#447]
Hi good day, I'm using nylas cloud since its release and I think than it's fantastic, now I'm working in a company than need some features in the email service and I think than maybe would be a great opportunity for use nylas, unfortunately I'm not totally clear about how the nylas cloud works, the api documentation is great https://www.nylas.com/cloud/docs but I'd like to know how is the process since the email is fire from the client until than it's received and what functionalities could provide me the nylas cloud

my company has several requirements like
1) we're using smartermail as email server, we want a client which can be autoconfigured, doing an api request now what email server address and ports must use
2) the attachments in the mail must be upload to our cloud so the final mail only must contain a link for this file
3) temporary mail: we're not sure about how achieve this, maybe would be possible replace the mail text for a link, if the link is clicked in a period of  time then render a page with the content...if not, then show than the link has expired

would be possible build this on the nylas infraestructure?

thank you so much and many thanks for build nylas

**Comment by sachinag-zz** [comment]
Heya!  Yeah, you should be able to do this with the Nylas Cloud APIs.  Shoot me an email at sachin [at] nylas.com and I'd be happy to answer any questions you have.
