### ISSUE TITLE
Is this, as a selfhosted solution, useless right now? What's the project's status?

### ISSUE THREAD

**Issue by kosciak9** [nylas/sync-engine#448]
After the transfer to the local Sync Engine in Nylas Mail, is it still possible to use this project on an own server? Is it even maintained anymore? It wasn't updated since March. I believe it would be good to give some information on project status in README.md or somewhere else :)

**Comment by sachinag-zz** [comment]
If you wanna run old N1 against sync-engine, you can do that.  Here's the last drop of N1: https://github.com/nylas/nylas-mail/releases/tag/1.5.0  

But the local sync engine in Nylas Mail means you don't need sync-engine.

**Comment by kosciak9** [comment]
But it's obsolete, and it won't be supported, right? Also, I would have to fork it and merge commits on top of "external-sync-engine" version of N1? :)

**Comment by aaron-chesley** [comment]
I recently asked Nylas if they were still supporting this and received the following response: 

_Hi Aaron,
Yes, it is, but it hasn't been updated in a while. However, we will be doing that soon. You can also use our API for free to integrate with up to 10 email accounts. Let me know if you have any other questions.
Thanks,
Lou_

**Comment by kosciak9** [comment]
Thanks for the heads up. Will be waiting for more updates then :)

On November 1, 2017 6:56:58 PM GMT+01:00, Aaron Chesley <notifications@github.com> wrote:
>I recently asked Nylas if they were still supporting this and received
>the following response: 
>
>_Hi Aaron,
>Yes, it is, but it hasn't been updated in a while. However, we will be
>doing that soon. You can also use our API for free to integrate with up
>to 10 email accounts. Let me know if you have any other questions.
>Thanks,
>Lou_
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nylas/sync-engine/issues/448#issuecomment-341187364

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by skunkwerk** [comment]
It's been a year since this project was updated - is it no longer supported?  Is Nylas no longer using this for their hosted version?

**Comment by andris9** [comment]
Anyone looking for an alternative - for IMAP access, there is [IMAP API](https://imapapi.com/) that manages IMAP connection pools and provides simple REST API to access messages.

**Comment by philfreo** [comment]
We are continuing to use/maintain this project at ~~https://github.com/closeio/nylas~~

EDIT: We have a new repo for further development: https://github.com/closeio/sync-engine

**Comment by philfreo** [comment]
Update: Close is now maintaining our version of sync-engine at https://github.com/closeio/sync-engine

Lots of improvements coming soon. We continue to use this in production.

**Comment by kosciak9** [comment]
No movement on this issue should point you in right direction dear reader :(
