### ISSUE TITLE
Partial Sync and documentation

### ISSUE THREAD

**Issue by JAB-Freeware** [nylas/sync-engine#454]
I understand the reasons behind doing a full copy of the mailserver instead of proxying. I have two concerns, however:

1) Are newest messages synced first? Otherwise an inbox with thousands of emails could takes several minutes before the user can see recent messages.

2) Would it be possible to modify the code so it only partially syncs? I could add an API endpoint to sync more. Basically I want to self host, but it seems like a waste to store all the user's emails when instead I could sync the most recent 100 in each folder, for example. If they need more the sync engine would just sync the next 100.  Is there a reason this isn't a feature? Is there an underlying problem with this approach that I should be aware of?

3) I setup some webhooks in the hosted portal, but I see no documentation here for adding the webhook callback address in self-hosted versions, so the only method I can figure out is repeatedly calling /messages.

Thanks! Awesome system btw.

**Comment by JAB-Freeware** [comment]
A reputation of ignoring issues is not really how you gain respect in the open source world... There are tons of open issues that have not been answered.

**Comment by khamidou** [comment]
Hi @JAB-Freeware! To answer your questions:
1. Yes, we prioritize syncing new messages first.
2. No, the sync engine is built around the assumption that our customers want access to their complete inbox. Changing the sync engine to support partial syncs would be a significant project.
3. Webhooks are unfortunately only supported in the hosted version of the sync-engine. However, you can use our [delta streaming API](https://docs.nylas.com/reference) if you want to get updated about new changes quickly.

Regards,
