### ISSUE TITLE
Vagrant can't forward port

### ISSUE THREAD

**Issue by mrcasals** [nylas/sync-engine#63]
Hi!

I don't know if this is the best place for this, but I'll try. I installed VirtualBox and Vagrant on my 10.7.4 Mac. I downloaded this repo and executed `vagrant up`, but then I got this error:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 9200 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 9200, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
```

I don't know which process is using the port 9200, but this makes `vagrant up` fail and thus can't execute `vagrant ssh`. Any ideas?

Thank you! :)

**Comment by jaimeiniesta** [comment]
This is again an issue, port 9200 is back on https://github.com/nylas/sync-engine/commit/153dd117240856caee01757831b5230e74aba6c6
