### ISSUE TITLE
Quote detection failure in forwarded message

### ISSUE THREAD

**Issue by grinich** [nylas/sync-engine#84]
From Duane (Bitlogica):

Forwarding from a gmail account to a gmail account (or to yourself with a gmail account) causes the quoted text to be completely removed.

I haven't dug into this, but it definitely sounds like a bug!

**Comment by alokhan** [comment]
Hi is quoted text stripping reenable ?

**Comment by spang** [comment]
Hi @alokhan, no we haven't re-enabled quote stripping yet. We've experimented with a few different strategies, but rolling it out in production requires careful testing given the volume of potential edge cases. Thanks for your suggestions!
