### ISSUE TITLE
can't find sodium.h on Ubuntu (not in vagrant)

### ISSUE THREAD

**Issue by alltom** [nylas/sync-engine#95]
I tried installing Inbox on terminal.com, but the setup script failed. Here's a snapshot (which includes scroll-back, so you can see the script output): https://www.terminal.com/tiny/V6yKVSNCVM

What I did was:
1. Go to Terminal.com and launch an Ubuntu 14 instance
2. Install git, then clone the inbox repo.
3. `sudo ./setup.sh` (you're root, but the script looks for `$SUDO_USER`

The `python bin/create-db` step fails trying to build something that requires `sodium.h`.

AFAIK, Terminal.com isn't one of your supported hosts, but since commits like 69685d6 claim to deal with this issue, I thought you might like to know.

**Comment by vinceasurion** [comment]
> This seems to be a manifestation of [pyca/pynacl#79](https://github.com/pyca/pynacl/issues/79)
> 
> On a recent Debian-based system, a workaround is to install the `libsodium-dev` package if it's available. If not, you can build and install libsodium manually.
> 
> I'll update setup.sh to do this automatically in the vagrant VM.

Thanks Solved my problem!
